# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    
      # AttachmentType - Supported attachment types. This property corresponds to the `attachments_supported`
      #  server metadata which was added by the third implementer's draft of OpenID Connect
      #  for Identity Assurance 1.0.
      # 
      class AttachmentType < T::Enum


        enums do
          EMBEDDED = new('EMBEDDED')
          EXTERNAL = new('EXTERNAL')
        end
      end
    end
  end
end
