# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components

      class AuditLogEntry
        extend T::Sig
        include Crystalline::MetadataFields

        # The audit event type (e.g. service.create, security.login).
        field :event, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('event') } }
        # Whether the action completed successfully or failed.
        field :status, Crystalline::Nilable.new(Models::Components::Status), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('status'), 'decoder': ::Authlete::Utils.enum_from_string(Models::Components::Status, true) } }
        # The cluster or region where the event occurred.
        field :cluster, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('cluster') } }
        # The API path that triggered the event.
        field :path, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('path') } }
        # The IP address of the client that performed the action.
        field :remote_addr, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('remoteAddr') } }
        # The user agent of the client.
        field :user_agent, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('userAgent') } }
        # The user or token that performed the action.
        field :user, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('user') } }
        # Additional event-specific metadata.
        field :details, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('details') } }
        # When the event occurred (ISO 8601). May be null for entries without a recorded
        # timestamp; such entries are only returned on the first page of results.
        #
        field :timestamp, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('timestamp'), 'decoder': ::Authlete::Utils.datetime_from_iso_format(true) } }

        sig { params(event: T.nilable(::String), status: T.nilable(Models::Components::Status), cluster: T.nilable(::String), path: T.nilable(::String), remote_addr: T.nilable(::String), user_agent: T.nilable(::String), user: T.nilable(::String), details: T.nilable(T::Hash[Symbol, ::Object]), timestamp: T.nilable(::DateTime)).void }
        def initialize(event: nil, status: nil, cluster: nil, path: nil, remote_addr: nil, user_agent: nil, user: nil, details: nil, timestamp: nil)
          @event = event
          @status = status
          @cluster = cluster
          @path = path
          @remote_addr = remote_addr
          @user_agent = user_agent
          @user = user
          @details = details
          @timestamp = timestamp
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @event == other.event
          return false unless @status == other.status
          return false unless @cluster == other.cluster
          return false unless @path == other.path
          return false unless @remote_addr == other.remote_addr
          return false unless @user_agent == other.user_agent
          return false unless @user == other.user
          return false unless @details == other.details
          return false unless @timestamp == other.timestamp
          true
        end
      end
    end
  end
end
