# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    
      # AuthorizationResponseAction - The next action that the authorization server implementation should take.
      class AuthorizationResponseAction < T::Enum


        enums do
          INTERNAL_SERVER_ERROR = new('INTERNAL_SERVER_ERROR')
          BAD_REQUEST = new('BAD_REQUEST')
          LOCATION = new('LOCATION')
          FORM = new('FORM')
          NO_INTERACTION = new('NO_INTERACTION')
          INTERACTION = new('INTERACTION')
        end
      end
    end
  end
end
