# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components

      class AuthorizationDetailsElement
        extend T::Sig
        include Crystalline::MetadataFields

        # The type of this element.
        # 
        # From _"OAuth 2.0 Rich Authorization Requests"_: _"The type of authorization data as a string.
        # This field MAY define which other elements are allowed in the request. This element is REQUIRED."_
        # 
        # This property is always NOT `null`.
        # 
        field :type, ::String, { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('type'), required: true } }
        # The resources and/or resource servers. This property may be `null`.
        # 
        # From _"OAuth 2.0 Rich Authorization Requests"_: _"An array of strings representing the location of
        # the resource or resource server. This is typically composed of URIs."_
        # 
        # This property may be `null`.
        # 
        field :locations, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('locations') } }
        # The actions.
        # 
        # From _"OAuth 2.0 Rich Authorization Requests"_: _"An array of strings representing the kinds of actions
        # to be taken at the resource. The values of the strings are determined by the API being protected."_
        # 
        # This property may be `null`.
        # 
        field :actions, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('actions') } }
        # From _"OAuth 2.0 Rich Authorization Requests"_: _"An array of strings representing the kinds of data being requested
        # from the resource."_
        # 
        # This property may be `null`.
        # 
        field :data_types, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('dataTypes') } }
        # The identifier of a specific resource.
        # From _"OAuth 2.0 Rich Authorization Requests"_: _"A string identifier indicating a specific resource available at the API."_
        # 
        # This property may be `null`.
        # 
        field :identifier, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('identifier') } }
        # The types or levels of privilege.
        # From "OAuth 2.0 Rich Authorization Requests": _"An array of strings representing the types or
        # levels of privilege being requested at the resource."_
        # 
        # This property may be `null`.
        # 
        field :privileges, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('privileges') } }
        # The RAR request in the JSON format excluding the pre-defined attributes such as `type` and `locations`.
        # The content and semantics are specific to the deployment and the use case implemented.
        # 
        field :other_fields, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('otherFields') } }

        sig { params(type: ::String, locations: T.nilable(T::Array[::String]), actions: T.nilable(T::Array[::String]), data_types: T.nilable(T::Array[::String]), identifier: T.nilable(::String), privileges: T.nilable(T::Array[::String]), other_fields: T.nilable(::String)).void }
        def initialize(type:, locations: nil, actions: nil, data_types: nil, identifier: nil, privileges: nil, other_fields: nil)
          @type = type
          @locations = locations
          @actions = actions
          @data_types = data_types
          @identifier = identifier
          @privileges = privileges
          @other_fields = other_fields
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @type == other.type
          return false unless @locations == other.locations
          return false unless @actions == other.actions
          return false unless @data_types == other.data_types
          return false unless @identifier == other.identifier
          return false unless @privileges == other.privileges
          return false unless @other_fields == other.other_fields
          true
        end
      end
    end
  end
end
