# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class AuthorizationRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # OAuth 2.0 authorization request parameters which are the request parameters that the OAuth 2.0 authorization endpoint of
        # the authorization server implementation received from the client application.
        # 
        # The value of parameters is either (1) the entire query string when the HTTP method of the request from the client application is `GET`
        # or (2) the entire entity body (which is formatted in `application/x-www-form-urlencoded`) when the HTTP method of the request from
        # the client application is `POST`.
        # 
        field :parameters, ::String, { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('parameters'), required: true }, 'form': { 'field_name': 'parameters' } }
        # The arbitrary text to be attached to the ticket that will be issued from the `/auth/authorization`
        # API.
        # 
        # The text can be retrieved later by the `/auth/authorization/ticket/info` API and can be updated
        # by the `/auth/authorization/ticket/update` API.
        # 
        # The text will be compressed and encrypted when it is saved in the Authlete database.
        # 
        field :context, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('context') }, 'form': { 'field_name': 'context' } }
        # Options for [OAuth Client ID Metadata Document](https://datatracker.ietf.org/doc/draft-ietf-oauth-client-id-metadata-document/) (CIMD).
        # 
        # These options allow per-request control over CIMD behavior, taking precedence over service-level configuration when provided.
        # 
        field :cimd_options, Crystalline::Nilable.new(Models::Components::CimdOptions), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('cimdOptions') }, 'form': { 'field_name': 'cimdOptions', 'json': true } }

        sig { params(parameters: ::String, context: T.nilable(::String), cimd_options: T.nilable(Models::Components::CimdOptions)).void }
        def initialize(parameters:, context: nil, cimd_options: nil)
          @parameters = parameters
          @context = context
          @cimd_options = cimd_options
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @parameters == other.parameters
          return false unless @context == other.context
          return false unless @cimd_options == other.cimd_options
          true
        end
      end
    end
  end
end
