# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class AuthorizationTicketInfoRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The ticket that has been issued from the `/auth/authorization` API.
        field :ticket, ::String, { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('ticket'), required: true }, 'form': { 'field_name': 'ticket' } }

        sig { params(ticket: ::String).void }
        def initialize(ticket:)
          @ticket = ticket
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @ticket == other.ticket
          true
        end
      end
    end
  end
end
