# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class AuthorizationTicketUpdateResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # Information about the ticket.
        field :info, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('info') } }
        # The result of the /auth/authorization/ticket/info API call.
        field :action, Crystalline::Nilable.new(Models::Components::AuthorizationTicketUpdateResponseAction), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('action'), 'decoder': Utils.enum_from_string(Models::Components::AuthorizationTicketUpdateResponseAction, true) } }
        # The code which represents the result of the API call.
        field :result_code, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('resultCode') } }
        # A short message which explains the result of the API call.
        field :result_message, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('resultMessage') } }

        sig { params(info: T.nilable(::String), action: T.nilable(Models::Components::AuthorizationTicketUpdateResponseAction), result_code: T.nilable(::String), result_message: T.nilable(::String)).void }
        def initialize(info: nil, action: nil, result_code: nil, result_message: nil)
          @info = info
          @action = action
          @result_code = result_code
          @result_message = result_message
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @info == other.info
          return false unless @action == other.action
          return false unless @result_code == other.result_code
          return false unless @result_message == other.result_message
          true
        end
      end
    end
  end
end
