# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class AuthorizationTicketInfo
        extend T::Sig
        include Crystalline::MetadataFields

        # The arbitrary text attached to the ticket.
        # 
        field :context, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('context') } }

        sig { params(context: T.nilable(::String)).void }
        def initialize(context: nil)
          @context = context
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @context == other.context
          true
        end
      end
    end
  end
end
