# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
      # BackchannelAuthenticationCompleteResponseAction - The next action that the authorization server implementation should take.
      # 
      class BackchannelAuthenticationCompleteResponseAction < T::Enum


        enums do
          SERVER_ERROR = new('SERVER_ERROR')
          NO_ACTION = new('NO_ACTION')
          NOTIFICATION = new('NOTIFICATION')
        end
      end
    end
  end
end
