# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
      # BatchKind - The kind of batch operation.
      class BatchKind < T::Enum


        enums do
          CREATE = new('CREATE')
        end
      end
    end
  end
end
