# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class ClaimType < T::Enum


        enums do
          NORMAL = new('NORMAL')
          AGGREGATED = new('AGGREGATED')
          DISTRIBUTED = new('DISTRIBUTED')
        end
      end
    end
  end
end
