# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components

      class ClientAuthorizationDeleteResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # The code which represents the result of the API call.
        field :result_code, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('resultCode') } }
        # A short message which explains the result of the API call.
        field :result_message, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('resultMessage') } }
        # A short message which explains the result of the API call.
        field :service_api_key, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('serviceApiKey') } }
        # Get the client ID.
        field :client_id, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientId') } }
        # Get the subject (= unique identifier) of the user
        # who has granted authorization to the client.
        # 
        field :subject, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('subject') } }
        # Get the scopes granted to the client application by the last
        # authorization process by the user (who is identified by the
        # subject).
        # 
        field :latest_granted_scopes, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('latestGrantedScopes') } }
        # Get the scopes granted to the client application by all the
        # past authorization processes. Note that revoked scopes are
        # not included.
        # 
        field :merged_granted_scopes, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('mergedGrantedScopes') } }
        # Get the timestamp in milliseconds since Unix epoch
        # at which this record was modified.
        # 
        field :modified_at, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('modifiedAt') } }

        sig { params(result_code: T.nilable(::String), result_message: T.nilable(::String), service_api_key: T.nilable(::Integer), client_id: T.nilable(::Integer), subject: T.nilable(::String), latest_granted_scopes: T.nilable(T::Array[::String]), merged_granted_scopes: T.nilable(T::Array[::String]), modified_at: T.nilable(::Integer)).void }
        def initialize(result_code: nil, result_message: nil, service_api_key: nil, client_id: nil, subject: nil, latest_granted_scopes: nil, merged_granted_scopes: nil, modified_at: nil)
          @result_code = result_code
          @result_message = result_message
          @service_api_key = service_api_key
          @client_id = client_id
          @subject = subject
          @latest_granted_scopes = latest_granted_scopes
          @merged_granted_scopes = merged_granted_scopes
          @modified_at = modified_at
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @result_code == other.result_code
          return false unless @result_message == other.result_message
          return false unless @service_api_key == other.service_api_key
          return false unless @client_id == other.client_id
          return false unless @subject == other.subject
          return false unless @latest_granted_scopes == other.latest_granted_scopes
          return false unless @merged_granted_scopes == other.merged_granted_scopes
          return false unless @modified_at == other.modified_at
          true
        end
      end
    end
  end
end
