# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    
      # ClientRegistrationResponseAction - The next action that the authorization server implementation should take.
      # 
      class ClientRegistrationResponseAction < T::Enum


        enums do
          BAD_REQUEST = new('BAD_REQUEST')
          CREATED = new('CREATED')
          DELETED = new('DELETED')
          INTERNAL_SERVER_ERROR = new('INTERNAL_SERVER_ERROR')
          OK = new('OK')
          UNAUTHORIZED = new('UNAUTHORIZED')
          UPDATED = new('UPDATED')
        end
      end
    end
  end
end
