# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class ClientAuthorizationGetListResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # Start index of search results (inclusive).
        # 
        field :start, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('start') } }
        # End index of search results (exclusive).
        # 
        field :end_, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('end') } }
        # Unique ID of a client developer.
        # 
        field :developer, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('developer') } }
        # Unique user ID of an end-user.
        # 
        field :subject, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('subject') } }
        # Unique ID of a client developer.
        # 
        field :total_count, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('totalCount') } }
        # An array of clients.
        # 
        field :clients, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::ClientLimited)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clients') } }

        sig { params(start: T.nilable(::Integer), end_: T.nilable(::Integer), developer: T.nilable(::String), subject: T.nilable(::String), total_count: T.nilable(::Integer), clients: T.nilable(T::Array[Models::Components::ClientLimited])).void }
        def initialize(start: nil, end_: nil, developer: nil, subject: nil, total_count: nil, clients: nil)
          @start = start
          @end_ = end_
          @developer = developer
          @subject = subject
          @total_count = total_count
          @clients = clients
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @start == other.start
          return false unless @end_ == other.end_
          return false unless @developer == other.developer
          return false unless @subject == other.subject
          return false unless @total_count == other.total_count
          return false unless @clients == other.clients
          true
        end
      end
    end
  end
end
