# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class ClientLimitedAuthorization
        extend T::Sig
        include Crystalline::MetadataFields

        # The sequential number of the client. The value of this property is assigned by Authlete.
        # 
        field :number, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('number') } }
        # The name of the client application. This property corresponds to `client_name` in
        # [OpenID Connect Dynamic Client Registration 1.0, 2. Client Metadata](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata).
        # 
        field :client_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientName') } }
        # Client names with language tags. If the client application has different names for different
        # languages, this property can be used to register the names.
        # 
        field :client_names, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::TaggedValue)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientNames') } }
        # The description about the client application.
        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('description') } }
        # Descriptions about the client application with language tags. If the client application has different
        # descriptions for different languages, this property can be used to register the descriptions.
        # 
        field :descriptions, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::TaggedValue)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('descriptions') } }
        # The client identifier used in Authlete API calls. The value of this property is assigned by Authlete.
        field :client_id, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientId') } }
        # The value of the client's `client_id` property used in OAuth and OpenID Connect calls. By
        # default, this is a string version of the `clientId` property.
        # 
        field :client_id_alias, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientIdAlias') } }
        # Deprecated. Always set to `true`.
        field :client_id_alias_enabled, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientIdAliasEnabled') } }
        # The client type, either `CONFIDENTIAL` or `PUBLIC`. See [RFC 6749, 2.1. Client Types](https://datatracker.ietf.org/doc/html/rfc6749#section-2.1)
        # for details.
        # 
        field :client_type, Crystalline::Nilable.new(Models::Components::ClientType), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientType'), 'decoder': Utils.enum_from_string(Models::Components::ClientType, true) } }
        # The URL pointing to the logo image of the client application.
        # 
        # This property corresponds to `logo_uri` in [OpenID Connect Dynamic Client Registration 1.0, 2.
        # Client Metadata](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata).
        # 
        field :logo_uri, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('logoUri') } }
        # Logo image URLs with language tags. If the client application has different logo images for
        # different languages, this property can be used to register URLs of the images.
        # 
        field :logo_uris, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::TaggedValue)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('logoUris') } }
        # The URL pointing to the "Terms Of Service" page.
        # 
        # This property corresponds to `tos_uri` in
        # [OpenID Connect Dynamic Client Registration 1.0, 2. Client Metadata](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata).
        # 
        field :tos_uri, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('tosUri') } }
        # URLs of "Terms Of Service" pages with language tags.
        # 
        # If the client application has different "Terms Of Service" pages for different languages,
        # this property can be used to register the URLs.
        # 
        field :tos_uris, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::TaggedValue)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('tosUris') } }
        # The URL pointing to the page which describes the policy as to how end-user's profile data is used.
        # 
        # This property corresponds to `policy_uri` in
        # [OpenID Connect Dynamic Client Registration 1.0, 2. Client Metadata](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata).
        # 
        field :policy_uri, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('policyUri') } }
        # URLs of policy pages with language tags.
        # If the client application has different policy pages for different languages, this property can be used to register the URLs.
        # 
        field :policy_uris, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::TaggedValue)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('policyUris') } }

        sig { params(number: T.nilable(::Integer), client_name: T.nilable(::String), client_names: T.nilable(T::Array[Models::Components::TaggedValue]), description: T.nilable(::String), descriptions: T.nilable(T::Array[Models::Components::TaggedValue]), client_id: T.nilable(::Integer), client_id_alias: T.nilable(::String), client_id_alias_enabled: T.nilable(T::Boolean), client_type: T.nilable(Models::Components::ClientType), logo_uri: T.nilable(::String), logo_uris: T.nilable(T::Array[Models::Components::TaggedValue]), tos_uri: T.nilable(::String), tos_uris: T.nilable(T::Array[Models::Components::TaggedValue]), policy_uri: T.nilable(::String), policy_uris: T.nilable(T::Array[Models::Components::TaggedValue])).void }
        def initialize(number: nil, client_name: nil, client_names: nil, description: nil, descriptions: nil, client_id: nil, client_id_alias: nil, client_id_alias_enabled: nil, client_type: nil, logo_uri: nil, logo_uris: nil, tos_uri: nil, tos_uris: nil, policy_uri: nil, policy_uris: nil)
          @number = number
          @client_name = client_name
          @client_names = client_names
          @description = description
          @descriptions = descriptions
          @client_id = client_id
          @client_id_alias = client_id_alias
          @client_id_alias_enabled = client_id_alias_enabled
          @client_type = client_type
          @logo_uri = logo_uri
          @logo_uris = logo_uris
          @tos_uri = tos_uri
          @tos_uris = tos_uris
          @policy_uri = policy_uri
          @policy_uris = policy_uris
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @number == other.number
          return false unless @client_name == other.client_name
          return false unless @client_names == other.client_names
          return false unless @description == other.description
          return false unless @descriptions == other.descriptions
          return false unless @client_id == other.client_id
          return false unless @client_id_alias == other.client_id_alias
          return false unless @client_id_alias_enabled == other.client_id_alias_enabled
          return false unless @client_type == other.client_type
          return false unless @logo_uri == other.logo_uri
          return false unless @logo_uris == other.logo_uris
          return false unless @tos_uri == other.tos_uri
          return false unless @tos_uris == other.tos_uris
          return false unless @policy_uri == other.policy_uri
          return false unless @policy_uris == other.policy_uris
          true
        end
      end
    end
  end
end
