# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    
      # ClientRegistrationType - Values for the `client_registration_types` RP metadata and the
      #  `client_registration_types_supported` OP metadata that are defined in
      #  [OpenID Connect Federation 1.0](https://openid.net/specs/openid-connect-federation-1_0.html).
      # 
      class ClientRegistrationType < T::Enum


        enums do
          AUTOMATIC = new('AUTOMATIC')
          EXPLICIT = new('EXPLICIT')
        end
      end
    end
  end
end
