# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components

      class ClientAuthorizationGetListRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Unique user ID of an end-user.
        field :subject, ::String, { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('subject'), required: true }, 'form': { 'field_name': 'subject' } }
        # Unique ID of a client developer.
        field :developer, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('developer') }, 'form': { 'field_name': 'developer' } }
        # Start index of search results (inclusive).
        field :start, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('start') }, 'form': { 'field_name': 'start' } }
        # End index of search results (exclusive).
        field :end_, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('end') }, 'form': { 'field_name': 'end' } }

        sig { params(subject: ::String, developer: T.nilable(::String), start: T.nilable(::Integer), end_: T.nilable(::Integer)).void }
        def initialize(subject:, developer: nil, start: nil, end_: nil)
          @subject = subject
          @developer = developer
          @start = start
          @end_ = end_
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @subject == other.subject
          return false unless @developer == other.developer
          return false unless @start == other.start
          return false unless @end_ == other.end_
          true
        end
      end
    end
  end
end
