# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class ClientSecretUpdateRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The new value of the client secret. Valid characters for a client secret are `A-Z`, `a-z`, `0-9`,
        # `-`, and `_`. The maximum length of a client secret is 86.
        # 
        field :client_secret, ::String, { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientSecret'), required: true }, 'form': { 'field_name': 'clientSecret' } }

        sig { params(client_secret: ::String).void }
        def initialize(client_secret:)
          @client_secret = client_secret
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @client_secret == other.client_secret
          true
        end
      end
    end
  end
end
