# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components

      class ClientFlagUpdateResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # The code which represents the result of the API call.
        field :result_code, ::String, { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('resultCode'), required: true } }
        # A short message which explains the result of the API call.
        field :result_message, ::String, { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('resultMessage'), required: true } }

        sig { params(result_code: ::String, result_message: ::String).void }
        def initialize(result_code:, result_message:)
          @result_code = result_code
          @result_message = result_message
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @result_code == other.result_code
          return false unless @result_message == other.result_message
          true
        end
      end
    end
  end
end
