# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class ClientLimited
        extend T::Sig
        include Crystalline::MetadataFields

        # The sequential number of the client. The value of this property is assigned by Authlete.
        # 
        field :number, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('number') } }
        # The name of the client application. This property corresponds to `client_name` in
        # [OpenID Connect Dynamic Client Registration 1.0, 2. Client Metadata](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata).
        # 
        field :client_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientName') } }
        # Client names with language tags. If the client application has different names for different
        # languages, this property can be used to register the names.
        # 
        field :client_names, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::TaggedValue)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientNames') } }
        # The description about the client application.
        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('description') } }
        # Descriptions about the client application with language tags. If the client application has different
        # descriptions for different languages, this property can be used to register the descriptions.
        # 
        field :descriptions, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::TaggedValue)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('descriptions') } }
        # The client identifier used in Authlete API calls. The value of this property is assigned by Authlete.
        field :client_id, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientId') } }
        # The value of the client's `client_id` property used in OAuth and OpenID Connect calls. By
        # default, this is a string version of the `clientId` property.
        # 
        field :client_id_alias, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientIdAlias') } }
        # Deprecated. Always set to `true`.
        field :client_id_alias_enabled, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientIdAliasEnabled') } }
        # The client type, either `CONFIDENTIAL` or `PUBLIC`. See [RFC 6749, 2.1. Client Types](https://datatracker.ietf.org/doc/html/rfc6749#section-2.1)
        # for details.
        # 
        field :client_type, Crystalline::Nilable.new(Models::Components::ClientType), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientType'), 'decoder': Utils.enum_from_string(Models::Components::ClientType, true) } }

        sig { params(number: T.nilable(::Integer), client_name: T.nilable(::String), client_names: T.nilable(T::Array[Models::Components::TaggedValue]), description: T.nilable(::String), descriptions: T.nilable(T::Array[Models::Components::TaggedValue]), client_id: T.nilable(::Integer), client_id_alias: T.nilable(::String), client_id_alias_enabled: T.nilable(T::Boolean), client_type: T.nilable(Models::Components::ClientType)).void }
        def initialize(number: nil, client_name: nil, client_names: nil, description: nil, descriptions: nil, client_id: nil, client_id_alias: nil, client_id_alias_enabled: nil, client_type: nil)
          @number = number
          @client_name = client_name
          @client_names = client_names
          @description = description
          @descriptions = descriptions
          @client_id = client_id
          @client_id_alias = client_id_alias
          @client_id_alias_enabled = client_id_alias_enabled
          @client_type = client_type
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @number == other.number
          return false unless @client_name == other.client_name
          return false unless @client_names == other.client_names
          return false unless @description == other.description
          return false unless @descriptions == other.descriptions
          return false unless @client_id == other.client_id
          return false unless @client_id_alias == other.client_id_alias
          return false unless @client_id_alias_enabled == other.client_id_alias_enabled
          return false unless @client_type == other.client_type
          true
        end
      end
    end
  end
end
