# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class CredentialIssuanceOrder
        extend T::Sig
        include Crystalline::MetadataFields

        # The identifier of a credential request.
        field :request_identifier, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('requestIdentifier') } }
        # The additional payload that will be added into a credential to be issued.
        field :credential_payload, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('credentialPayload') } }
        # The flag indicating whether to defer credential issuance.
        field :issuance_deferred, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('issuanceDeferred') } }
        # The duration of a credential to be issued.
        field :credential_duration, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('credentialDuration') } }
        # The key ID of a private key that should be used for signing a credential
        # to be issued.
        # 
        field :signing_key_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('signingKeyId') } }

        sig { params(request_identifier: T.nilable(::String), credential_payload: T.nilable(::String), issuance_deferred: T.nilable(T::Boolean), credential_duration: T.nilable(::Integer), signing_key_id: T.nilable(::String)).void }
        def initialize(request_identifier: nil, credential_payload: nil, issuance_deferred: nil, credential_duration: nil, signing_key_id: nil)
          @request_identifier = request_identifier
          @credential_payload = credential_payload
          @issuance_deferred = issuance_deferred
          @credential_duration = credential_duration
          @signing_key_id = signing_key_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @request_identifier == other.request_identifier
          return false unless @credential_payload == other.credential_payload
          return false unless @issuance_deferred == other.issuance_deferred
          return false unless @credential_duration == other.credential_duration
          return false unless @signing_key_id == other.signing_key_id
          true
        end
      end
    end
  end
end
