# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class CredentialRequestInfo
        extend T::Sig
        include Crystalline::MetadataFields

        # The identifier of the credential offer.
        field :identifier, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('identifier') } }
        # The value of the format parameter in the credential request.
        field :format, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('format') } }
        # The binding key specified by the proof in the credential request.
        field :binding_key, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('bindingKey') } }
        # The binding keys specified by the proofs in the credential request.
        field :binding_keys, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('bindingKeys') } }
        # The details about the credential request.
        field :details, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('details') } }

        sig { params(identifier: T.nilable(::String), format: T.nilable(::String), binding_key: T.nilable(::String), binding_keys: T.nilable(T::Array[::String]), details: T.nilable(::String)).void }
        def initialize(identifier: nil, format: nil, binding_key: nil, binding_keys: nil, details: nil)
          @identifier = identifier
          @format = format
          @binding_key = binding_key
          @binding_keys = binding_keys
          @details = details
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @identifier == other.identifier
          return false unless @format == other.format
          return false unless @binding_key == other.binding_key
          return false unless @binding_keys == other.binding_keys
          return false unless @details == other.details
          true
        end
      end
    end
  end
end
