# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components

      class DeviceAuthorizationResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # The code which represents the result of the API call.
        field :result_code, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('resultCode') } }
        # A short message which explains the result of the API call.
        field :result_message, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('resultMessage') } }
        # The next action that the authorization server implementation should take.
        field :action, Crystalline::Nilable.new(Models::Components::DeviceAuthorizationResponseAction), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('action'), 'decoder': Utils.enum_from_string(Models::Components::DeviceAuthorizationResponseAction, true) } }
        # The content that the authorization server implementation is to return to the client
        # application. Its format varies depending on the value of `action` parameter.
        # 
        field :response_content, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('responseContent') } }
        # The client ID of the client application that has made the device authorization request.
        # 
        field :client_id, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientId') } }
        # The client ID alias of the client application that has made the device authorization
        # request.
        # 
        field :client_id_alias, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientIdAlias') } }
        # `true` if the value of the client_id request parameter included in the device authorization
        # request is the client ID alias. `false` if the value is the original numeric client ID.
        # 
        field :client_id_alias_used, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientIdAliasUsed') } }
        # The name of the client application which has made the device authorization request.
        # 
        field :client_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientName') } }
        # The client authentication method that should be performed at the device authorization
        # endpoint.
        # 
        field :client_auth_method, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientAuthMethod') } }
        # The scopes requested by the device authorization request.
        # 
        # Basically, this property holds the value of the scope request parameter in the device
        # authorization request. However, because unregistered scopes are dropped on Authlete
        # side, if the `scope` request parameter contains unknown scopes, the list returned by
        # this property becomes different from the value of the `scope` request parameter.
        # 
        # Note that `description` property and `descriptions` property of each scope object in the
        # array contained in this property is always `null` even if descriptions of the scopes
        # are registered.
        # 
        field :scopes, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::Scope)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('scopes') } }
        # The names of the claims which were requested indirectly via some special scopes.
        # See [5.4. Requesting Claims using Scope Values](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims)
        # in OpenID Connect Core 1.0 for details.
        # 
        field :claim_names, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('claimNames') } }
        # The list of ACR values requested by the device authorization request.
        # 
        # Basically, this property holds the value of the `acr_values` request parameter in the
        # device authorization request. However, because unsupported ACR values are dropped
        # on Authlete side, if the `acr_values` request parameter contains unrecognized ACR values,
        # the list returned by this property becomes different from the value of the `acr_values`
        # request parameter.
        # 
        field :acrs, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('acrs') } }
        # The device verification code. This corresponds to the `device_code` property in the
        # response to the client.
        # 
        field :device_code, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('deviceCode') } }
        # The end-user verification code. This corresponds to the `user_code` property in the
        # response to the client.
        # 
        field :user_code, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('userCode') } }
        # The end-user verification URI. This corresponds to the `verification_uri` property in
        # the response to the client.
        # 
        field :verification_uri, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('verificationUri') } }
        # The end-user verification URI that includes the end-user verification code. This corresponds
        # to the `verification_uri_complete` property in the response to the client.
        # 
        field :verification_uri_complete, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('verificationUriComplete') } }
        # The duration of the device verification code in seconds. This corresponds to the `expires_in`
        # property in the response to the client.
        # 
        field :expires_in, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('expiresIn') } }
        # The minimum amount of time in seconds that the client must wait for between polling
        # requests to the token endpoint. This corresponds to the `interval` property in the response
        # to the client.
        # 
        field :interval, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('interval') } }
        # The warnings raised during processing the backchannel authentication request.
        # 
        field :warnings, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('warnings') } }
        # The resources specified by the `resource` request parameters. See "Resource Indicators
        # for OAuth 2.0" for details.
        # 
        field :resources, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('resources') } }
        # The authorization details. This represents the value of the `authorization_details`
        # request parameter in the preceding device authorization request which is defined in
        # "OAuth 2.0 Rich Authorization Requests".
        # 
        field :authorization_details, Crystalline::Nilable.new(Models::Components::AuthzDetails), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('authorizationDetails') } }
        # The attributes of this service that the client application belongs to.
        # 
        field :service_attributes, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::Pair)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('serviceAttributes') } }
        # The attributes of the client.
        # 
        field :client_attributes, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::Pair)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientAttributes') } }
        # The dynamic scopes which the client application requested by the scope request parameter.
        # 
        field :dynamic_scopes, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::DynamicScope)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('dynamicScopes') } }
        # The grant management action of the device authorization request.
        # 
        # The `grant_management_action` request parameter is defined in
        # [Grant Management for OAuth 2.0](https://openid.net/specs/fapi-grant-management.html).
        # 
        field :gm_action, Crystalline::Nilable.new(Models::Components::GrantManagementAction), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('gmAction'), 'decoder': Utils.enum_from_string(Models::Components::GrantManagementAction, true) } }
        # the value of the `grant_id` request parameter of the device authorization request.
        # 
        # The `grant_id` request parameter is defined in
        # [Grant Management for OAuth 2.0](https://openid.net/specs/fapi-grant-management.html)
        # , which is supported by Authlete 2.3 and newer versions.
        # 
        field :grant_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('grantId') } }

        field :grant, Crystalline::Nilable.new(Models::Components::Grant), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('grant') } }
        # The subject identifying the user who has given the grant identified
        # by the `grant\_id` request parameter of the device authorization
        # request.
        # Authlete 2.3 and newer versions support [Grant Management
        # for OAuth 2.0](https://openid.net/specs/fapi-grant-management.html). An authorization request may contain a `grant\_id`
        # request parameter which is defined in the specification. If the value of
        # the request parameter is valid, {@link #getGrantSubject()} will return
        # the subject of the user who has given the grant to the client application.
        # Authorization server implementations may use the value returned from
        # {@link #getGrantSubject()} in order to determine the user to authenticate.
        # The user your system will authenticate during the authorization process
        # (or has already authenticated) may be different from the user of the
        # grant. The first implementer's draft of "Grant Management for OAuth 2.0"
        # does not mention anything about the case, so the behavior in the case is
        # left to implementations. Authlete will not perform the grant management
        # action when the `subject` passed to Authlete does not match the
        # user of the grant.
        # 
        field :grant_subject, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('grantSubject') } }
        # The entity ID of the client.
        # 
        field :client_entity_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientEntityId') } }
        # Flag which indicates whether the entity ID of the client was used when the request for the access token was made.
        # 
        field :client_entity_id_used, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientEntityIdUsed') } }
        # The location of the client's metadata document that was used to resolve client metadata.
        # 
        # This property is set when client metadata was retrieved via the [OAuth Client ID Metadata Document](https://datatracker.ietf.org/doc/draft-ietf-oauth-client-id-metadata-document/) (CIMD) mechanism.
        # 
        field :metadata_document_location, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('metadataDocumentLocation') } }
        # Flag indicating whether a metadata document was used to resolve client metadata for this request.
        # 
        # When `true`, the client metadata was retrieved via the CIMD mechanism rather than from the Authlete database.
        # 
        field :metadata_document_used, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('metadataDocumentUsed') } }

        sig { params(result_code: T.nilable(::String), result_message: T.nilable(::String), action: T.nilable(Models::Components::DeviceAuthorizationResponseAction), response_content: T.nilable(::String), client_id: T.nilable(::Integer), client_id_alias: T.nilable(::String), client_id_alias_used: T.nilable(T::Boolean), client_name: T.nilable(::String), client_auth_method: T.nilable(::String), scopes: T.nilable(T::Array[Models::Components::Scope]), claim_names: T.nilable(T::Array[::String]), acrs: T.nilable(T::Array[::String]), device_code: T.nilable(::String), user_code: T.nilable(::String), verification_uri: T.nilable(::String), verification_uri_complete: T.nilable(::String), expires_in: T.nilable(::Integer), interval: T.nilable(::Integer), warnings: T.nilable(T::Array[::String]), resources: T.nilable(T::Array[::String]), authorization_details: T.nilable(Models::Components::AuthzDetails), service_attributes: T.nilable(T::Array[Models::Components::Pair]), client_attributes: T.nilable(T::Array[Models::Components::Pair]), dynamic_scopes: T.nilable(T::Array[Models::Components::DynamicScope]), gm_action: T.nilable(Models::Components::GrantManagementAction), grant_id: T.nilable(::String), grant: T.nilable(Models::Components::Grant), grant_subject: T.nilable(::String), client_entity_id: T.nilable(::String), client_entity_id_used: T.nilable(T::Boolean), metadata_document_location: T.nilable(::String), metadata_document_used: T.nilable(T::Boolean)).void }
        def initialize(result_code: nil, result_message: nil, action: nil, response_content: nil, client_id: nil, client_id_alias: nil, client_id_alias_used: nil, client_name: nil, client_auth_method: nil, scopes: nil, claim_names: nil, acrs: nil, device_code: nil, user_code: nil, verification_uri: nil, verification_uri_complete: nil, expires_in: nil, interval: nil, warnings: nil, resources: nil, authorization_details: nil, service_attributes: nil, client_attributes: nil, dynamic_scopes: nil, gm_action: nil, grant_id: nil, grant: nil, grant_subject: nil, client_entity_id: nil, client_entity_id_used: nil, metadata_document_location: nil, metadata_document_used: nil)
          @result_code = result_code
          @result_message = result_message
          @action = action
          @response_content = response_content
          @client_id = client_id
          @client_id_alias = client_id_alias
          @client_id_alias_used = client_id_alias_used
          @client_name = client_name
          @client_auth_method = client_auth_method
          @scopes = scopes
          @claim_names = claim_names
          @acrs = acrs
          @device_code = device_code
          @user_code = user_code
          @verification_uri = verification_uri
          @verification_uri_complete = verification_uri_complete
          @expires_in = expires_in
          @interval = interval
          @warnings = warnings
          @resources = resources
          @authorization_details = authorization_details
          @service_attributes = service_attributes
          @client_attributes = client_attributes
          @dynamic_scopes = dynamic_scopes
          @gm_action = gm_action
          @grant_id = grant_id
          @grant = grant
          @grant_subject = grant_subject
          @client_entity_id = client_entity_id
          @client_entity_id_used = client_entity_id_used
          @metadata_document_location = metadata_document_location
          @metadata_document_used = metadata_document_used
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @result_code == other.result_code
          return false unless @result_message == other.result_message
          return false unless @action == other.action
          return false unless @response_content == other.response_content
          return false unless @client_id == other.client_id
          return false unless @client_id_alias == other.client_id_alias
          return false unless @client_id_alias_used == other.client_id_alias_used
          return false unless @client_name == other.client_name
          return false unless @client_auth_method == other.client_auth_method
          return false unless @scopes == other.scopes
          return false unless @claim_names == other.claim_names
          return false unless @acrs == other.acrs
          return false unless @device_code == other.device_code
          return false unless @user_code == other.user_code
          return false unless @verification_uri == other.verification_uri
          return false unless @verification_uri_complete == other.verification_uri_complete
          return false unless @expires_in == other.expires_in
          return false unless @interval == other.interval
          return false unless @warnings == other.warnings
          return false unless @resources == other.resources
          return false unless @authorization_details == other.authorization_details
          return false unless @service_attributes == other.service_attributes
          return false unless @client_attributes == other.client_attributes
          return false unless @dynamic_scopes == other.dynamic_scopes
          return false unless @gm_action == other.gm_action
          return false unless @grant_id == other.grant_id
          return false unless @grant == other.grant
          return false unless @grant_subject == other.grant_subject
          return false unless @client_entity_id == other.client_entity_id
          return false unless @client_entity_id_used == other.client_entity_id_used
          return false unless @metadata_document_location == other.metadata_document_location
          return false unless @metadata_document_used == other.metadata_document_used
          true
        end
      end
    end
  end
end
