# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
      # DeviceCompleteResponseAction - The next action that the authorization server implementation should take.
      # 
      class DeviceCompleteResponseAction < T::Enum


        enums do
          SERVER_ERROR = new('SERVER_ERROR')
          USER_CODE_NOT_EXIST = new('USER_CODE_NOT_EXIST')
          USER_CODE_EXPIRED = new('USER_CODE_EXPIRED')
          INVALID_REQUEST = new('INVALID_REQUEST')
          SUCCESS = new('SUCCESS')
        end
      end
    end
  end
end
