# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class DeviceVerificationRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # A user code.
        # 
        field :user_code, ::String, { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('userCode'), required: true }, 'form': { 'field_name': 'userCode' } }

        sig { params(user_code: ::String).void }
        def initialize(user_code:)
          @user_code = user_code
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @user_code == other.user_code
          true
        end
      end
    end
  end
end
