# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
      # EntityType - The entity type, as defined in OpenID Federation 1.0.
      #
      class EntityType < T::Enum
        enums do
          OPENID_RELYING_PARTY = new('OPENID_RELYING_PARTY')
          OPENID_PROVIDER = new('OPENID_PROVIDER')
          OAUTH_AUTHORIZATION_SERVER = new('OAUTH_AUTHORIZATION_SERVER')
          OAUTH_CLIENT = new('OAUTH_CLIENT')
          OAUTH_RESOURCE = new('OAUTH_RESOURCE')
          FEDERATION_ENTITY = new('FEDERATION_ENTITY')
          OPENID_CREDENTIAL_ISSUER = new('OPENID_CREDENTIAL_ISSUER')
        end
      end
    end
  end
end
