# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    
      # FederationRegistrationResponseAction - The next action that the authorization server implementation should take.
      class FederationRegistrationResponseAction < T::Enum


        enums do
          OK = new('OK')
          BAD_REQUEST = new('BAD_REQUEST')
          NOT_FOUND = new('NOT_FOUND')
          INTERNAL_SERVER_ERROR = new('INTERNAL_SERVER_ERROR')
        end
      end
    end
  end
end
