# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components

      class GMResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # The code which represents the result of the API call.
        field :result_code, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('resultCode') } }
        # A short message which explains the result of the API call.
        field :result_message, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('resultMessage') } }
        # The next action that the authorization server implementation should take.
        field :action, Crystalline::Nilable.new(Models::Components::GMResponseAction), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('action'), 'decoder': Utils.enum_from_string(Models::Components::GMResponseAction, true) } }
        # The content that the authorization server implementation is to return to the client application.
        # Its format varies depending on the value of `action` parameter.
        # 
        field :response_content, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('responseContent') } }
        # Get the expected nonce value for DPoP proof JWT, which should be used
        # as the value of the `DPoP-Nonce` HTTP header.
        # 
        field :dpop_nonce, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('dpopNonce') } }

        sig { params(result_code: T.nilable(::String), result_message: T.nilable(::String), action: T.nilable(Models::Components::GMResponseAction), response_content: T.nilable(::String), dpop_nonce: T.nilable(::String)).void }
        def initialize(result_code: nil, result_message: nil, action: nil, response_content: nil, dpop_nonce: nil)
          @result_code = result_code
          @result_message = result_message
          @action = action
          @response_content = response_content
          @dpop_nonce = dpop_nonce
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @result_code == other.result_code
          return false unless @result_message == other.result_message
          return false unless @action == other.action
          return false unless @response_content == other.response_content
          return false unless @dpop_nonce == other.dpop_nonce
          true
        end
      end
    end
  end
end
