# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    
      # GMResponseAction - The next action that the authorization server implementation should take.
      class GMResponseAction < T::Enum


        enums do
          OK = new('OK')
          NO_CONTENT = new('NO_CONTENT')
          UNAUTHORIZED = new('UNAUTHORIZED')
          FORBIDDEN = new('FORBIDDEN')
          NOT_FOUND = new('NOT_FOUND')
          CALLER_ERROR = new('CALLER_ERROR')
          AUTHLETE_ERROR = new('AUTHLETE_ERROR')
        end
      end
    end
  end
end
