# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    
      # GrantManagementAction - The grant management action of the device authorization request.
      # 
      # The `grant_management_action` request parameter is defined in
      # [Grant Management for OAuth 2.0](https://openid.net/specs/fapi-grant-management.html).
      # 
      class GrantManagementAction < T::Enum


        enums do
          CREATE = new('CREATE')
          QUERY = new('QUERY')
          REPLACE = new('REPLACE')
          REVOKE = new('REVOKE')
          MERGE = new('MERGE')
        end
      end
    end
  end
end
