# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components

      class GrantScope
        extend T::Sig
        include Crystalline::MetadataFields

        # Space-delimited scopes.
        # 
        field :scope, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('scope') } }
        # List of resource indicators.
        # 
        field :resource, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('resource') } }

        sig { params(scope: T.nilable(::String), resource: T.nilable(T::Array[::String])).void }
        def initialize(scope: nil, resource: nil)
          @scope = scope
          @resource = resource
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @scope == other.scope
          return false unless @resource == other.resource
          true
        end
      end
    end
  end
end
