# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
      # GrantType - The grant type of the access token when the access token was created.
      # 
      class GrantType < T::Enum


        enums do
          AUTHORIZATION_CODE = new('AUTHORIZATION_CODE')
          IMPLICIT = new('IMPLICIT')
          PASSWORD = new('PASSWORD')
          CLIENT_CREDENTIALS = new('CLIENT_CREDENTIALS')
          REFRESH_TOKEN = new('REFRESH_TOKEN')
          CIBA = new('CIBA')
          DEVICE_CODE = new('DEVICE_CODE')
          TOKEN_EXCHANGE = new('TOKEN_EXCHANGE')
          JWT_BEARER = new('JWT_BEARER')
          PRE_AUTHORIZED_CODE = new('PRE_AUTHORIZED_CODE')
        end
      end
    end
  end
end
