# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    
      # HskGetListResponseAction - Result of the API call
      class HskGetListResponseAction < T::Enum


        enums do
          SUCCESS = new('SUCCESS')
          INVALID_REQUEST = new('INVALID_REQUEST')
          SERVER_ERROR = new('SERVER_ERROR')
        end
      end
    end
  end
end
