# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
      # HskDeleteResponseAction - Result of the API call
      class HskDeleteResponseAction < T::Enum


        enums do
          SUCCESS = new('SUCCESS')
          INVALID_REQUEST = new('INVALID_REQUEST')
          NOT_FOUND = new('NOT_FOUND')
          SERVER_ERROR = new('SERVER_ERROR')
        end
      end
    end
  end
end
