# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
      # JweEnc - This is the encryption algorithm to be used when encrypting a JWT on client or server side.
      # Depending upon the context, this refers to encryption done by the client or by the server. For instance:
      #   - as `authorizationEncryptionEnc` value, it refers to the encryption algorithm used by server when creating a JARM response
      #   - as `requestEncryptionEnc` value, it refers to the expected encryption algorithm used by the client when encrypting a Request Object
      #   - as `idTokenEncryptionEnc` value, it refers to the algorithm used by the server to encrypt id_tokens
      # 
      class JweEnc < T::Enum


        enums do
          A128_CBC_HS256 = new('A128CBC_HS256')
          A192_CBC_HS384 = new('A192CBC_HS384')
          A256_CBC_HS512 = new('A256CBC_HS512')
          A128_GCM = new('A128GCM')
          A192_GCM = new('A192GCM')
          A256_GCM = new('A256GCM')
        end
      end
    end
  end
end
