# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class NativeSsoLogoutResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # The code which represents the result of the API call.
        field :result_code, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('resultCode') } }
        # A short message which explains the result of the API call.
        field :result_message, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('resultMessage') } }
        # The next action that the API caller should take.
        # 
        field :action, Crystalline::Nilable.new(Models::Components::NativeSsoLogoutResponseAction), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('action'), 'decoder': Utils.enum_from_string(Models::Components::NativeSsoLogoutResponseAction, true) } }
        # The number of deleted access/refresh token records.
        # 
        field :count, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('count') } }

        sig { params(result_code: T.nilable(::String), result_message: T.nilable(::String), action: T.nilable(Models::Components::NativeSsoLogoutResponseAction), count: T.nilable(::Integer)).void }
        def initialize(result_code: nil, result_message: nil, action: nil, count: nil)
          @result_code = result_code
          @result_message = result_message
          @action = action
          @count = count
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @result_code == other.result_code
          return false unless @result_message == other.result_message
          return false unless @action == other.action
          return false unless @count == other.count
          true
        end
      end
    end
  end
end
