# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class NativeSsoLogoutRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The session ID of a user's authentication session.
        # 
        field :session_id, ::String, { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('sessionId'), required: true } }

        sig { params(session_id: ::String).void }
        def initialize(session_id:)
          @session_id = session_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @session_id == other.session_id
          true
        end
      end
    end
  end
end
