# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class ResponseType < T::Enum


        enums do
          NONE = new('NONE')
          CODE = new('CODE')
          TOKEN = new('TOKEN')
          ID_TOKEN = new('ID_TOKEN')
          CODE_TOKEN = new('CODE_TOKEN')
          CODE_ID_TOKEN = new('CODE_ID_TOKEN')
          ID_TOKEN_TOKEN = new('ID_TOKEN_TOKEN')
          CODE_ID_TOKEN_TOKEN = new('CODE_ID_TOKEN_TOKEN')
        end
      end
    end
  end
end
