# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components

      class RevocationRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # OAuth 2.0 token revocation request parameters which are the request parameters that the OAuth 2.0 token revocation endpoint
        # ([RFC 7009](https://datatracker.ietf.org/doc/html/rfc7009)) of the authorization server implementation received from the
        # client application.
        # 
        # The value of parameters is the entire entity body (which is formatted in `application/x-www-form-urlencoded`) of the request
        # from the client application.
        # 
        field :parameters, ::String, { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('parameters'), required: true }, 'form': { 'field_name': 'parameters' } }
        # The client ID extracted from `Authorization` header of the revocation request from the client application.
        # 
        # If the revocation endpoint of the authorization server implementation supports Basic Authentication
        # as a means of client authentication, and the request from the client application contains its client ID in
        # `Authorization` header, the value should be extracted and set to this parameter.
        # 
        field :client_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientId') }, 'form': { 'field_name': 'clientId' } }
        # The client secret extracted from `Authorization` header of the revocation request from the client application.
        # 
        # If the revocation endpoint of the authorization server implementation supports basic authentication as a means of
        # client authentication, and the request from the client application contained its client secret in `Authorization` header,
        # the value should be extracted and set to this parameter.
        # 
        field :client_secret, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientSecret') }, 'form': { 'field_name': 'clientSecret' } }
        # The client certificate used in the TLS connection between the client application and the revocation endpoint.
        # 
        field :client_certificate, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientCertificate') }, 'form': { 'field_name': 'clientCertificate' } }
        # The certificate path presented by the client during client authentication.
        # 
        field :client_certificate_path, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientCertificatePath') }, 'form': { 'field_name': 'clientCertificatePath' } }
        # The value of the `OAuth-Client-Attestation` HTTP header, which is defined in the specification
        # of [OAuth 2.0 Attestation-Based Client Authentication](https://datatracker.ietf.org/doc/draft-ietf-oauth-attestation-based-client-auth/).
        # 
        field :oauth_client_attestation, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('oauthClientAttestation') }, 'form': { 'field_name': 'oauthClientAttestation' } }
        # The value of the `OAuth-Client-Attestation-PoP` HTTP header, which is defined in the specification
        # of [OAuth 2.0 Attestation-Based Client Authentication](https://datatracker.ietf.org/doc/draft-ietf-oauth-attestation-based-client-auth/).
        # 
        field :oauth_client_attestation_pop, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('oauthClientAttestationPop') }, 'form': { 'field_name': 'oauthClientAttestationPop' } }

        sig { params(parameters: ::String, client_id: T.nilable(::String), client_secret: T.nilable(::String), client_certificate: T.nilable(::String), client_certificate_path: T.nilable(T::Array[::String]), oauth_client_attestation: T.nilable(::String), oauth_client_attestation_pop: T.nilable(::String)).void }
        def initialize(parameters:, client_id: nil, client_secret: nil, client_certificate: nil, client_certificate_path: nil, oauth_client_attestation: nil, oauth_client_attestation_pop: nil)
          @parameters = parameters
          @client_id = client_id
          @client_secret = client_secret
          @client_certificate = client_certificate
          @client_certificate_path = client_certificate_path
          @oauth_client_attestation = oauth_client_attestation
          @oauth_client_attestation_pop = oauth_client_attestation_pop
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @parameters == other.parameters
          return false unless @client_id == other.client_id
          return false unless @client_secret == other.client_secret
          return false unless @client_certificate == other.client_certificate
          return false unless @client_certificate_path == other.client_certificate_path
          return false unless @oauth_client_attestation == other.oauth_client_attestation
          return false unless @oauth_client_attestation_pop == other.oauth_client_attestation_pop
          true
        end
      end
    end
  end
end
