# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components

      class ServiceJwksGetResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # An array of [JWK](https://datatracker.ietf.org/doc/html/rfc7517)s.
        field :keys, Crystalline::Nilable.new(Crystalline::Array.new(Crystalline::Hash.new(Symbol, ::Object))), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('keys') } }

        sig { params(keys: T.nilable(T::Array[T::Hash[Symbol, ::Object]])).void }
        def initialize(keys: nil)
          @keys = keys
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @keys == other.keys
          true
        end
      end
    end
  end
end
