# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class ServiceProfile < T::Enum


        enums do
          FAPI = new('FAPI')
          OPEN_BANKING = new('OPEN_BANKING')
        end
      end
    end
  end
end
