# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components

      class ServiceCreateIdpRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The numeric ID of the organization the service belongs to.
        field :organization_id, ::Integer, { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('organizationId'), required: true } }
        # The numeric ID of the API server to create the service on. Official SDKs inject
        # this automatically for known Authlete clusters, so it can be omitted there;
        # all other callers must provide it.
        #
        field :api_server_id, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('apiServerId') } }

        field :service, Crystalline::Nilable.new(Models::Components::ServiceInput), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('service') } }

        sig { params(organization_id: ::Integer, api_server_id: T.nilable(::Integer), service: T.nilable(Models::Components::ServiceInput)).void }
        def initialize(organization_id:, api_server_id: nil, service: nil)
          @organization_id = organization_id
          @api_server_id = api_server_id
          @service = service
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @organization_id == other.organization_id
          return false unless @api_server_id == other.api_server_id
          return false unless @service == other.service
          true
        end
      end
    end
  end
end
