# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components

      class ServiceGetListResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # Start index (inclusive) of the result set. The default value is 0. Must not be a negative
        # number.
        # 
        field :start, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('start') } }
        # Start index (inclusive) of the result set. The default value is 0. Must not be a negative
        # number.
        # 
        field :end_, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('end') } }
        # Total number of services owned by the service owner. This doesn't mean the number of services
        # contained in the response.
        # 
        field :total_count, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('totalCount') } }
        # An array of services.
        # 
        field :services, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::Service)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('services') } }

        sig { params(start: T.nilable(::Integer), end_: T.nilable(::Integer), total_count: T.nilable(::Integer), services: T.nilable(T::Array[Models::Components::Service])).void }
        def initialize(start: nil, end_: nil, total_count: nil, services: nil)
          @start = start
          @end_ = end_
          @total_count = total_count
          @services = services
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @start == other.start
          return false unless @end_ == other.end_
          return false unless @total_count == other.total_count
          return false unless @services == other.services
          true
        end
      end
    end
  end
end
