# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
      # StandardIntrospectionResponseAction - The next action that the authorization server implementation should take.
      class StandardIntrospectionResponseAction < T::Enum


        enums do
          INTERNAL_SERVER_ERROR = new('INTERNAL_SERVER_ERROR')
          BAD_REQUEST = new('BAD_REQUEST')
          OK = new('OK')
          JWT = new('JWT')
        end
      end
    end
  end
end
