# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class SupportedSnse < T::Enum


        enums do
          FACEBOOK = new('FACEBOOK')
        end
      end
    end
  end
end
