# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class TokenIssueRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The ticket issued from Authlete `/auth/token` API.
        # 
        field :ticket, ::String, { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('ticket'), required: true }, 'form': { 'field_name': 'ticket' } }
        # The subject (= unique identifier) of the authenticated user.
        # 
        field :subject, ::String, { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('subject'), required: true }, 'form': { 'field_name': 'subject' } }
        # Extra properties to associate with a newly created access token. Note that properties parameter is accepted only
        # when `Content-Type` of the request is `application/json`, so don't use `application/x-www-form-urlencoded`
        # if you want to specify properties.
        # 
        field :properties, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::Property)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('properties') }, 'form': { 'field_name': 'properties', 'json': true } }
        # Additional claims that are added to the payload part of the JWT access token.
        # 
        field :jwt_at_claims, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('jwtAtClaims') }, 'form': { 'field_name': 'jwtAtClaims' } }
        # The representation of an access token that may be issued as a result of the Authlete API call.
        # 
        field :access_token, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('accessToken') }, 'form': { 'field_name': 'accessToken' } }
        # The duration (in seconds) of the access token that may be issued as a result of the Authlete
        # API call.
        # 
        # When this request parameter holds a positive integer, it is used as the duration of the access
        # token in. In other cases, this request parameter is ignored.
        # 
        field :access_token_duration, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('accessTokenDuration') }, 'form': { 'field_name': 'accessTokenDuration' } }
        # The duration (in seconds) of the refresh token that may be issued as a result of the Authlete
        # API call.
        # 
        # When this request parameter holds a positive integer, it is used as the duration of the refresh
        # token in. In other cases, this request parameter is ignored.
        # 
        field :refresh_token_duration, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('refreshTokenDuration') }, 'form': { 'field_name': 'refreshTokenDuration' } }

        sig { params(ticket: ::String, subject: ::String, properties: T.nilable(T::Array[Models::Components::Property]), jwt_at_claims: T.nilable(::String), access_token: T.nilable(::String), access_token_duration: T.nilable(::Integer), refresh_token_duration: T.nilable(::Integer)).void }
        def initialize(ticket:, subject:, properties: nil, jwt_at_claims: nil, access_token: nil, access_token_duration: nil, refresh_token_duration: nil)
          @ticket = ticket
          @subject = subject
          @properties = properties
          @jwt_at_claims = jwt_at_claims
          @access_token = access_token
          @access_token_duration = access_token_duration
          @refresh_token_duration = refresh_token_duration
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @ticket == other.ticket
          return false unless @subject == other.subject
          return false unless @properties == other.properties
          return false unless @jwt_at_claims == other.jwt_at_claims
          return false unless @access_token == other.access_token
          return false unless @access_token_duration == other.access_token_duration
          return false unless @refresh_token_duration == other.refresh_token_duration
          true
        end
      end
    end
  end
end
