# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    
      # TokenFailRequestReason - The reason of the failure of the token request.
      # 
      class TokenFailRequestReason < T::Enum


        enums do
          UNKNOWN = new('UNKNOWN')
          INVALID_RESOURCE_OWNER_CREDENTIALS = new('INVALID_RESOURCE_OWNER_CREDENTIALS')
          INVALID_TARGET = new('INVALID_TARGET')
        end
      end
    end
  end
end
