# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class TokenIssueResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # The code which represents the result of the API call.
        field :result_code, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('resultCode') } }
        # A short message which explains the result of the API call.
        field :result_message, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('resultMessage') } }
        # The next action that the authorization server implementation should take.
        field :action, Crystalline::Nilable.new(Models::Components::TokenIssueResponseAction), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('action'), 'decoder': Utils.enum_from_string(Models::Components::TokenIssueResponseAction, true) } }
        # The content that the authorization server implementation is to return to the client application.
        # Its format is JSON.
        # 
        field :response_content, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('responseContent') } }
        # The newly issued access token. This parameter is a non-null value only when the value of `action` parameter is `OK`.
        field :access_token, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('accessToken') } }
        # The datetime at which the newly issued access token will expire.
        # The value is represented in milliseconds since the Unix epoch (1970-01-01).
        # 
        field :access_token_expires_at, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('accessTokenExpiresAt') } }
        # The duration of the newly issued access token in seconds.
        field :access_token_duration, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('accessTokenDuration') } }
        # The refresh token. This parameter is a non-null value only when `action` is `OK` and the service supports the refresh token flow.
        # If `refreshTokenKept` is set to `false`, a new refresh token is issued and the old refresh token used in the refresh token flow
        # is invalidated. On the contrary, if `refreshTokenKept` is set to `true`, the refresh token itself is not refreshed.
        # 
        field :refresh_token, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('refreshToken') } }
        # The datetime at which the newly issued refresh token will expire.
        # The value is represented in milliseconds since the Unix epoch (1970-01-01).
        # 
        field :refresh_token_expires_at, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('refreshTokenExpiresAt') } }
        # The duration of the newly issued refresh token in seconds.
        field :refresh_token_duration, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('refreshTokenDuration') } }
        # The client ID.
        field :client_id, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientId') } }
        # The client ID alias. If the client did not have an alias, this parameter is `null`.
        # 
        field :client_id_alias, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientIdAlias') } }
        # The flag which indicates whether the client ID alias was used when the token request was made.
        # `true` if the client ID alias was used when the token request was made.
        # 
        field :client_id_alias_used, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientIdAliasUsed') } }
        # The subject (= resource owner's ID) of the access token.
        # Even if an access token has been issued by calling `/api/auth/token` API, this parameter is `null` if the flow of the token request was
        # [Client Credentials Flow](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4) (`grant_type=client_credentials`) because it means
        # the access token is not associated with any specific end-user.
        # 
        field :subject, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('subject') } }
        # The scopes covered by the access token.
        field :scopes, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('scopes') } }
        # The extra properties associated with the access token.
        # This parameter is `null` when no extra property is associated with the issued access token.
        # 
        field :properties, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::Property)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('properties') } }
        # The newly issued access token in JWT format. If the authorization server is configured to issue JWT-based access tokens
        # (= if the service's `accessTokenSignAlg` value is a non-null value), a JWT-based access token is issued along with the
        # original random-string one.
        # 
        field :jwt_access_token, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('jwtAccessToken') } }
        # The target resources of the access token being issued. See "Resource Indicators for OAuth 2.0" for details.
        # 
        field :access_token_resources, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('accessTokenResources') } }
        # The authorization details. This represents the value of the `authorization_details`
        # request parameter in the preceding device authorization request which is defined in
        # "OAuth 2.0 Rich Authorization Requests".
        # 
        field :authorization_details, Crystalline::Nilable.new(Models::Components::AuthzDetails), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('authorizationDetails') } }
        # The attributes of this service that the client application belongs to.
        # 
        field :service_attributes, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::Pair)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('serviceAttributes') } }
        # The attributes of the client.
        # 
        field :client_attributes, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::Pair)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientAttributes') } }
        # The entity ID of the client.
        # 
        field :client_entity_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientEntityId') } }
        # Flag which indicates whether the entity ID of the client was used when the request for the access token was made.
        # 
        field :client_entity_id_used, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('clientEntityIdUsed') } }
        # The scopes associated with the refresh token. May be null.
        # 
        field :refresh_token_scopes, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('refreshTokenScopes') } }
        # The location of the client's metadata document that was used to resolve client metadata.
        # 
        # This property is set when client metadata was retrieved via the [OAuth Client ID Metadata Document](https://datatracker.ietf.org/doc/draft-ietf-oauth-client-id-metadata-document/) (CIMD) mechanism.
        # 
        field :metadata_document_location, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('metadataDocumentLocation') } }
        # Flag indicating whether a metadata document was used to resolve client metadata for this request.
        # 
        # When `true`, the client metadata was retrieved via the CIMD mechanism rather than from the Authlete database.
        # 
        field :metadata_document_used, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('metadataDocumentUsed') } }

        sig { params(result_code: T.nilable(::String), result_message: T.nilable(::String), action: T.nilable(Models::Components::TokenIssueResponseAction), response_content: T.nilable(::String), access_token: T.nilable(::String), access_token_expires_at: T.nilable(::Integer), access_token_duration: T.nilable(::Integer), refresh_token: T.nilable(::String), refresh_token_expires_at: T.nilable(::Integer), refresh_token_duration: T.nilable(::Integer), client_id: T.nilable(::Integer), client_id_alias: T.nilable(::String), client_id_alias_used: T.nilable(T::Boolean), subject: T.nilable(::String), scopes: T.nilable(T::Array[::String]), properties: T.nilable(T::Array[Models::Components::Property]), jwt_access_token: T.nilable(::String), access_token_resources: T.nilable(T::Array[::String]), authorization_details: T.nilable(Models::Components::AuthzDetails), service_attributes: T.nilable(T::Array[Models::Components::Pair]), client_attributes: T.nilable(T::Array[Models::Components::Pair]), client_entity_id: T.nilable(::String), client_entity_id_used: T.nilable(T::Boolean), refresh_token_scopes: T.nilable(T::Array[::String]), metadata_document_location: T.nilable(::String), metadata_document_used: T.nilable(T::Boolean)).void }
        def initialize(result_code: nil, result_message: nil, action: nil, response_content: nil, access_token: nil, access_token_expires_at: nil, access_token_duration: nil, refresh_token: nil, refresh_token_expires_at: nil, refresh_token_duration: nil, client_id: nil, client_id_alias: nil, client_id_alias_used: nil, subject: nil, scopes: nil, properties: nil, jwt_access_token: nil, access_token_resources: nil, authorization_details: nil, service_attributes: nil, client_attributes: nil, client_entity_id: nil, client_entity_id_used: nil, refresh_token_scopes: nil, metadata_document_location: nil, metadata_document_used: nil)
          @result_code = result_code
          @result_message = result_message
          @action = action
          @response_content = response_content
          @access_token = access_token
          @access_token_expires_at = access_token_expires_at
          @access_token_duration = access_token_duration
          @refresh_token = refresh_token
          @refresh_token_expires_at = refresh_token_expires_at
          @refresh_token_duration = refresh_token_duration
          @client_id = client_id
          @client_id_alias = client_id_alias
          @client_id_alias_used = client_id_alias_used
          @subject = subject
          @scopes = scopes
          @properties = properties
          @jwt_access_token = jwt_access_token
          @access_token_resources = access_token_resources
          @authorization_details = authorization_details
          @service_attributes = service_attributes
          @client_attributes = client_attributes
          @client_entity_id = client_entity_id
          @client_entity_id_used = client_entity_id_used
          @refresh_token_scopes = refresh_token_scopes
          @metadata_document_location = metadata_document_location
          @metadata_document_used = metadata_document_used
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @result_code == other.result_code
          return false unless @result_message == other.result_message
          return false unless @action == other.action
          return false unless @response_content == other.response_content
          return false unless @access_token == other.access_token
          return false unless @access_token_expires_at == other.access_token_expires_at
          return false unless @access_token_duration == other.access_token_duration
          return false unless @refresh_token == other.refresh_token
          return false unless @refresh_token_expires_at == other.refresh_token_expires_at
          return false unless @refresh_token_duration == other.refresh_token_duration
          return false unless @client_id == other.client_id
          return false unless @client_id_alias == other.client_id_alias
          return false unless @client_id_alias_used == other.client_id_alias_used
          return false unless @subject == other.subject
          return false unless @scopes == other.scopes
          return false unless @properties == other.properties
          return false unless @jwt_access_token == other.jwt_access_token
          return false unless @access_token_resources == other.access_token_resources
          return false unless @authorization_details == other.authorization_details
          return false unless @service_attributes == other.service_attributes
          return false unless @client_attributes == other.client_attributes
          return false unless @client_entity_id == other.client_entity_id
          return false unless @client_entity_id_used == other.client_entity_id_used
          return false unless @refresh_token_scopes == other.refresh_token_scopes
          return false unless @metadata_document_location == other.metadata_document_location
          return false unless @metadata_document_used == other.metadata_document_used
          true
        end
      end
    end
  end
end
