# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
      # TokenUpdateResponseAction - The next action that the authorization server implementation should take.
      class TokenUpdateResponseAction < T::Enum


        enums do
          INTERNAL_SERVER_ERROR = new('INTERNAL_SERVER_ERROR')
          BAD_REQUEST = new('BAD_REQUEST')
          FORBIDDEN = new('FORBIDDEN')
          NOT_FOUND = new('NOT_FOUND')
          OK = new('OK')
        end
      end
    end
  end
end
