# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    
      # TokenResponseAction - The next action that the authorization server implementation should take.
      class TokenResponseAction < T::Enum


        enums do
          INTERNAL_SERVER_ERROR = new('INTERNAL_SERVER_ERROR')
          INVALID_CLIENT = new('INVALID_CLIENT')
          BAD_REQUEST = new('BAD_REQUEST')
          PASSWORD = new('PASSWORD')
          OK = new('OK')
          TOKEN_EXCHANGE = new('TOKEN_EXCHANGE')
          JWT_BEARER = new('JWT_BEARER')
        end
      end
    end
  end
end
