# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components

      class VciBatchIssueRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The access token that came along with the credential request.
        field :access_token, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('accessToken') } }
        # The instructions for issuance of credentials and/or transaction IDs.
        field :orders, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::CredentialIssuanceOrder)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('orders') } }

        sig { params(access_token: T.nilable(::String), orders: T.nilable(T::Array[Models::Components::CredentialIssuanceOrder])).void }
        def initialize(access_token: nil, orders: nil)
          @access_token = access_token
          @orders = orders
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @access_token == other.access_token
          return false unless @orders == other.orders
          true
        end
      end
    end
  end
end
