# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components

      class VciOfferCreateRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The flag indicating whether the `authorization_code` object is
        # included in the `grants` object.
        # 
        field :authorization_code_grant_included, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('authorizationCodeGrantIncluded') }, 'form': { 'field_name': 'authorizationCodeGrantIncluded' } }
        # The flag indicating whether the `issuer_state` property is
        # included in the `authorization_code` object in the `grants`
        # object.
        # 
        field :issuer_state_included, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('issuerStateIncluded') }, 'form': { 'field_name': 'issuerStateIncluded' } }
        # The flag to include the
        # `urn:ietf:params:oauth:grant-type:pre-authorized_code` object
        # in the `grants` object.
        # 
        field :pre_authorized_code_grant_included, Crystalline::Nilable.new(Crystalline::Boolean.new), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('preAuthorizedCodeGrantIncluded') }, 'form': { 'field_name': 'preAuthorizedCodeGrantIncluded' } }
        # The subject associated with the credential offer.
        field :subject, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('subject') }, 'form': { 'field_name': 'subject' } }
        # The duration of the credential offer.
        field :duration, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('duration') }, 'form': { 'field_name': 'duration' } }
        # The general-purpose arbitrary string.
        field :context, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('context') }, 'form': { 'field_name': 'context' } }
        # Extra properties to associate with the credential offer.
        field :properties, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::Property)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('properties') }, 'form': { 'field_name': 'properties', 'json': true } }
        # Additional claims that are added to the payload part of the JWT
        # access token.
        # 
        field :jwt_at_claims, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('jwtAtClaims') }, 'form': { 'field_name': 'jwtAtClaims' } }
        # The time at which the user authentication was performed during
        # the course of issuing the credential offer.
        # 
        field :auth_time, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('authTime') }, 'form': { 'field_name': 'authTime' } }
        # The Authentication Context Class Reference of the user authentication
        # performed during the course of issuing the credential offer.
        # 
        field :acr, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('acr') }, 'form': { 'field_name': 'acr' } }
        # The value of the `credential_configuration_ids` array.
        # 
        # ```
        # {
        #   "credential_issuer": "...",
        #   "credential_configuration_ids": [ ... ],
        #   "grants": { ... }
        # }
        # ```
        # 
        # This property is mandatory.
        # 
        field :credential_configuration_ids, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('credentialConfigurationIds') }, 'form': { 'field_name': 'credentialConfigurationIds' } }
        # The transaction code that should be associated with the credential offer.
        # 
        # If this parameter is not empty and the `preAuthorizedCodeGrantIncluded` parameter is `true`, the
        # `urn:ietf:params:oauth:grant-type:pre-authorized_code` object will include the `tx_code` object.
        # 
        # The length of the value of this parameter will be used as the value of the `length` property in
        # the `tx_code` object.
        # 
        # ```
        # {
        #   "credential_issuer": "...",
        #   "credential_configuration_ids": [ ... ],
        #   "grants": {
        #     "urn:ietf:params:oauth:grant-type:pre-authorized_code": {
        #       "pre-authorized_code": "...",
        #       "tx_code": {
        #         "length": length
        #       }
        #     }
        #   }
        # }
        # ```
        # 
        field :tx_code, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('txCode') }, 'form': { 'field_name': 'txCode' } }
        # The input mode of the transaction code.
        # 
        # The value of this property will be used as the value of the `input_mode` property in the `tx_code`
        # object.
        # 
        # ```
        # {
        #   "credential_issuer": "...",
        #   "credential_configuration_ids": [ ... ],
        #   "grants": {
        #     "urn:ietf:params:oauth:grant-type:pre-authorized_code": {
        #       "pre-authorized_code": "...",
        #       "tx_code": {
        #         "length": length,
        #         "input_mode": "..."
        #       }
        #     }
        #   }
        # }
        # ```
        # 
        field :tx_code_input_mode, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('txCodeInputMode') }, 'form': { 'field_name': 'txCodeInputMode' } }
        # The description of the transaction code.
        # 
        # The value of this property will be used as the value of the `description` property in the `tx_code`
        # object.
        # 
        # ```
        # {
        #   "credential_issuer": "...",
        #   "credential_configuration_ids": [ ... ],
        #   "grants": {
        #     "urn:ietf:params:oauth:grant-type:pre-authorized_code": {
        #       "pre-authorized_code": "...",
        #       "tx_code": {
        #         "length": length,
        #         "description": "..."
        #       }
        #     }
        #   }
        # }
        # ```
        # 
        field :tx_code_description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('txCodeDescription') }, 'form': { 'field_name': 'txCodeDescription' } }

        sig { params(authorization_code_grant_included: T.nilable(T::Boolean), issuer_state_included: T.nilable(T::Boolean), pre_authorized_code_grant_included: T.nilable(T::Boolean), subject: T.nilable(::String), duration: T.nilable(::Integer), context: T.nilable(::String), properties: T.nilable(T::Array[Models::Components::Property]), jwt_at_claims: T.nilable(::String), auth_time: T.nilable(::Integer), acr: T.nilable(::String), credential_configuration_ids: T.nilable(T::Array[::String]), tx_code: T.nilable(::String), tx_code_input_mode: T.nilable(::String), tx_code_description: T.nilable(::String)).void }
        def initialize(authorization_code_grant_included: nil, issuer_state_included: nil, pre_authorized_code_grant_included: nil, subject: nil, duration: nil, context: nil, properties: nil, jwt_at_claims: nil, auth_time: nil, acr: nil, credential_configuration_ids: nil, tx_code: nil, tx_code_input_mode: nil, tx_code_description: nil)
          @authorization_code_grant_included = authorization_code_grant_included
          @issuer_state_included = issuer_state_included
          @pre_authorized_code_grant_included = pre_authorized_code_grant_included
          @subject = subject
          @duration = duration
          @context = context
          @properties = properties
          @jwt_at_claims = jwt_at_claims
          @auth_time = auth_time
          @acr = acr
          @credential_configuration_ids = credential_configuration_ids
          @tx_code = tx_code
          @tx_code_input_mode = tx_code_input_mode
          @tx_code_description = tx_code_description
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @authorization_code_grant_included == other.authorization_code_grant_included
          return false unless @issuer_state_included == other.issuer_state_included
          return false unless @pre_authorized_code_grant_included == other.pre_authorized_code_grant_included
          return false unless @subject == other.subject
          return false unless @duration == other.duration
          return false unless @context == other.context
          return false unless @properties == other.properties
          return false unless @jwt_at_claims == other.jwt_at_claims
          return false unless @auth_time == other.auth_time
          return false unless @acr == other.acr
          return false unless @credential_configuration_ids == other.credential_configuration_ids
          return false unless @tx_code == other.tx_code
          return false unless @tx_code_input_mode == other.tx_code_input_mode
          return false unless @tx_code_description == other.tx_code_description
          true
        end
      end
    end
  end
end
