# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class VciOfferInfoRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The identifier of the credential offer.
        field :identifier, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('identifier') }, 'form': { 'field_name': 'identifier' } }

        sig { params(identifier: T.nilable(::String)).void }
        def initialize(identifier: nil)
          @identifier = identifier
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @identifier == other.identifier
          true
        end
      end
    end
  end
end
