# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    
      # VciBatchIssueResponseAction - The next action that the implementation of the batch credential
      # endpoint should take.
      # 
      class VciBatchIssueResponseAction < T::Enum


        enums do
          OK = new('OK')
          UNAUTHORIZED = new('UNAUTHORIZED')
          FORBIDDEN = new('FORBIDDEN')
          INTERNAL_SERVER_ERROR = new('INTERNAL_SERVER_ERROR')
          CALLER_ERROR = new('CALLER_ERROR')
        end
      end
    end
  end
end
