# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class VciDeferredIssueRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :order, Crystalline::Nilable.new(Models::Components::CredentialIssuanceOrder), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('order') } }

        sig { params(order: T.nilable(Models::Components::CredentialIssuanceOrder)).void }
        def initialize(order: nil)
          @order = order
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @order == other.order
          true
        end
      end
    end
  end
end
