# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
    

      class VciSingleIssueRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The access token that came along with the credential request.
        field :access_token, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('accessToken') } }

        field :order, Crystalline::Nilable.new(Models::Components::CredentialIssuanceOrder), { 'format_json': { 'letter_case': ::Authlete::Utils.field_name('order') } }

        sig { params(access_token: T.nilable(::String), order: T.nilable(Models::Components::CredentialIssuanceOrder)).void }
        def initialize(access_token: nil, order: nil)
          @access_token = access_token
          @order = order
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @access_token == other.access_token
          return false unless @order == other.order
          true
        end
      end
    end
  end
end
