# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Components
      # VciMetadataResponseAction - The next action that the implementation of the credential issuer
      # metadata endpoint (`/.well-known/openid-credential-issuer`)
      # should take after getting a response from Authlete's
      # `/vci/metadata` API.
      # 
      class VciMetadataResponseAction < T::Enum


        enums do
          OK = new('OK')
          NOT_FOUND = new('NOT_FOUND')
          INTERNAL_SERVER_ERROR = new('INTERNAL_SERVER_ERROR')
        end
      end
    end
  end
end
