# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module Authlete
  autoload :Authlete, 'authlete/authlete'
  autoload :Service, 'authlete/service'
  autoload :Client, 'authlete/client'
  autoload :ClientManagement, 'authlete/client_management'
  autoload :Authorization, 'authlete/authorization'
  autoload :AuthorizationManagement, 'authlete/authorization_management'
  autoload :PushedAuthorization, 'authlete/pushedauthorization'
  autoload :Token, 'authlete/token'
  autoload :TokenManagement, 'authlete/token_management'
  autoload :Introspection, 'authlete/introspection'
  autoload :Revocation, 'authlete/revocation'
  autoload :Userinfo, 'authlete/userinfo'
  autoload :GrantManagement, 'authlete/grantmanagement'
  autoload :JWKSetEndpoint, 'authlete/jwk_set_endpoint'
  autoload :DynamicClientRegistration, 'authlete/dynamicclientregistration'
  autoload :Ciba, 'authlete/ciba'
  autoload :DeviceFlow, 'authlete/deviceflow'
  autoload :JoseObject, 'authlete/jose_object'
  autoload :Federation, 'authlete/federation'
  autoload :HardwareSecurityKeys, 'authlete/hardwaresecuritykeys'
  autoload :VerifiableCredentials, 'authlete/verifiablecredentials'
  autoload :NativeSso, 'authlete/nativesso'
  module Models
    autoload :Components, 'authlete/models/components'
    autoload :Operations, 'authlete/models/operations'
    autoload :Errors, 'authlete/models/errors'
    autoload :Callbacks, 'authlete/models/callbacks'
  end
end

require_relative 'authlete/utils/utils'
require_relative 'authlete/utils/request_bodies'
require_relative 'authlete/utils/query_params'
require_relative 'authlete/utils/forms'
require_relative 'authlete/utils/headers'
require_relative 'authlete/utils/url'
require_relative 'authlete/utils/security'
require_relative 'crystalline'
require_relative 'authlete/sdkconfiguration'
