# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Operations
      # AUDIT_ENTRIES_GET_IDP_API_RESPONSE_SERVER_IDP - IDP Server
      AUDIT_ENTRIES_GET_IDP_API_RESPONSE_SERVER_IDP = 'idp'
      AUDIT_ENTRIES_GET_IDP_API_RESPONSE_SERVERS = {
        # IDP Server
        AUDIT_ENTRIES_GET_IDP_API_RESPONSE_SERVER_IDP: 'https://login.authlete.com'
      }.freeze

      class AuditEntriesGetIdpApiResponse
        extend T::Sig
        include Crystalline::MetadataFields
        sig { returns(T.proc.returns(T.nilable(AuditEntriesGetIdpApiResponse))) }
        attr_accessor :next_page

        # HTTP response content type for this operation
        field :content_type, ::String
        # HTTP response status code for this operation
        field :status_code, ::Integer
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, ::Faraday::Response
        # A page of audit log entries matching the query.
        field :audit_entries_get_response, Crystalline::Nilable.new(Models::Components::AuditEntriesGetResponse)

        sig { params(content_type: ::String, status_code: ::Integer, raw_response: ::Faraday::Response, audit_entries_get_response: T.nilable(Models::Components::AuditEntriesGetResponse)).void }
        def initialize(content_type:, status_code:, raw_response:, audit_entries_get_response: nil)
          @content_type = content_type
          @status_code = status_code
          @raw_response = raw_response
          @audit_entries_get_response = audit_entries_get_response
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @content_type == other.content_type
          return false unless @status_code == other.status_code
          return false unless @raw_response == other.raw_response
          return false unless @audit_entries_get_response == other.audit_entries_get_response
          true
        end

        def each
          page = self
          loop do
            yield page
            next_page = page.next_page.call if page.next_page
            break if next_page.nil?
            page = T.must(next_page)
          end
        end
      end
    end
  end
end
