# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Operations

      class AuthTokenUpdateApiRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # A service ID.
        field :service_id, ::String, { 'path_param': { 'field_name': 'serviceId', 'style': 'simple', 'explode': false } }

        field :token_update_request, Models::Components::TokenUpdateRequest, { 'request': { 'media_type': 'application/json' } }

        sig { params(service_id: ::String, token_update_request: Models::Components::TokenUpdateRequest).void }
        def initialize(service_id:, token_update_request:)
          @service_id = service_id
          @token_update_request = token_update_request
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @service_id == other.service_id
          return false unless @token_update_request == other.token_update_request
          true
        end
      end
    end
  end
end
