# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Operations

      class AuthUserinfoIssueApiRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # A service ID.
        field :service_id, ::String, { 'path_param': { 'field_name': 'serviceId', 'style': 'simple', 'explode': false } }

        field :userinfo_issue_request, Models::Components::UserinfoIssueRequest, { 'request': { 'media_type': 'application/json' } }

        sig { params(service_id: ::String, userinfo_issue_request: Models::Components::UserinfoIssueRequest).void }
        def initialize(service_id:, userinfo_issue_request:)
          @service_id = service_id
          @userinfo_issue_request = userinfo_issue_request
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @service_id == other.service_id
          return false unless @userinfo_issue_request == other.userinfo_issue_request
          true
        end
      end
    end
  end
end
