# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Operations

      class AuthTokenCreateBatchStatusApiRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # A service ID.
        field :service_id, ::String, { 'path_param': { 'field_name': 'serviceId', 'style': 'simple', 'explode': false } }
        # A token batch request ID.
        # 
        field :token_batch_request_id, ::String, { 'path_param': { 'field_name': 'tokenBatchRequestId', 'style': 'simple', 'explode': false } }

        sig { params(service_id: ::String, token_batch_request_id: ::String).void }
        def initialize(service_id:, token_batch_request_id:)
          @service_id = service_id
          @token_batch_request_id = token_batch_request_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @service_id == other.service_id
          return false unless @token_batch_request_id == other.token_batch_request_id
          true
        end
      end
    end
  end
end
