# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Operations

      class BackchannelLogoutTokenApiRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # A service ID.
        field :service_id, ::String, { 'path_param': { 'field_name': 'serviceId', 'style': 'simple', 'explode': false } }

        field :backchannel_logout_token_request, Models::Components::BackchannelLogoutTokenRequest, { 'request': { 'media_type': 'application/json' } }

        sig { params(service_id: ::String, backchannel_logout_token_request: Models::Components::BackchannelLogoutTokenRequest).void }
        def initialize(service_id:, backchannel_logout_token_request:)
          @service_id = service_id
          @backchannel_logout_token_request = backchannel_logout_token_request
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @service_id == other.service_id
          return false unless @backchannel_logout_token_request == other.backchannel_logout_token_request
          true
        end
      end
    end
  end
end
