# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Operations

      class ClientUpdateApiResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # HTTP response content type for this operation
        field :content_type, ::String
        # HTTP response status code for this operation
        field :status_code, ::Integer
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, ::Faraday::Response

        field :client, Crystalline::Nilable.new(Models::Components::Client)

        sig { params(content_type: ::String, status_code: ::Integer, raw_response: ::Faraday::Response, client: T.nilable(Models::Components::Client)).void }
        def initialize(content_type:, status_code:, raw_response:, client: nil)
          @content_type = content_type
          @status_code = status_code
          @raw_response = raw_response
          @client = client
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @content_type == other.content_type
          return false unless @status_code == other.status_code
          return false unless @raw_response == other.raw_response
          return false unless @client == other.client
          true
        end
      end
    end
  end
end
