# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Operations
    

      class ClientAuthorizationGetListApiRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # A service ID.
        field :service_id, ::String, { 'path_param': { 'field_name': 'serviceId', 'style': 'simple', 'explode': false } }
        # Unique user ID of an end-user.
        # 
        field :subject_path_parameter, ::String, { 'path_param': { 'field_name': 'subject', 'style': 'simple', 'explode': false } }
        # Unique user ID of an end-user.
        # 
        field :subject_query_parameter, ::String, { 'query_param': { 'field_name': 'subject', 'style': 'form', 'explode': true } }
        # Unique ID of a client developer.
        # 
        field :developer, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'developer', 'style': 'form', 'explode': true } }
        # Start index of search results (inclusive). The default value is 0.
        field :start, Crystalline::Nilable.new(::Integer), { 'query_param': { 'field_name': 'start', 'style': 'form', 'explode': true } }
        # End index of search results (exclusive). The default value is 5.
        # 
        field :end_, Crystalline::Nilable.new(::Integer), { 'query_param': { 'field_name': 'end', 'style': 'form', 'explode': true } }

        sig { params(service_id: ::String, subject_path_parameter: ::String, subject_query_parameter: ::String, developer: T.nilable(::String), start: T.nilable(::Integer), end_: T.nilable(::Integer)).void }
        def initialize(service_id:, subject_path_parameter:, subject_query_parameter:, developer: nil, start: nil, end_: nil)
          @service_id = service_id
          @subject_path_parameter = subject_path_parameter
          @subject_query_parameter = subject_query_parameter
          @developer = developer
          @start = start
          @end_ = end_
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @service_id == other.service_id
          return false unless @subject_path_parameter == other.subject_path_parameter
          return false unless @subject_query_parameter == other.subject_query_parameter
          return false unless @developer == other.developer
          return false unless @start == other.start
          return false unless @end_ == other.end_
          true
        end
      end
    end
  end
end
