# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Operations

      class ClientGetListApiRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # A service ID.
        field :service_id, ::String, { 'path_param': { 'field_name': 'serviceId', 'style': 'simple', 'explode': false } }
        # The developer of client applications. The default value is null. If this parameter is not set
        # to `null`, client application of the specified developer are returned. Otherwise, all client
        # applications that belong to the service are returned.
        # 
        field :developer, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'developer', 'style': 'form', 'explode': true } }
        # Start index (inclusive) of the result set. The default value is 0. Must not be a negative number.
        field :start, Crystalline::Nilable.new(::Integer), { 'query_param': { 'field_name': 'start', 'style': 'form', 'explode': true } }
        # End index (exclusive) of the result set. The default value is 5. Must not be a negative number.
        field :end_, Crystalline::Nilable.new(::Integer), { 'query_param': { 'field_name': 'end', 'style': 'form', 'explode': true } }

        sig { params(service_id: ::String, developer: T.nilable(::String), start: T.nilable(::Integer), end_: T.nilable(::Integer)).void }
        def initialize(service_id:, developer: nil, start: nil, end_: nil)
          @service_id = service_id
          @developer = developer
          @start = start
          @end_ = end_
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @service_id == other.service_id
          return false unless @developer == other.developer
          return false unless @start == other.start
          return false unless @end_ == other.end_
          true
        end
      end
    end
  end
end
