# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Operations

      class ClientGrantedScopesGetApiPostRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # A service ID.
        field :service_id, ::String, { 'path_param': { 'field_name': 'serviceId', 'style': 'simple', 'explode': false } }
        # A client ID.
        # 
        field :client_id, ::String, { 'path_param': { 'field_name': 'clientId', 'style': 'simple', 'explode': false } }

        field :request_body, Models::Operations::ClientGrantedScopesGetApiPostRequestBody, { 'request': { 'media_type': 'application/json' } }

        sig { params(service_id: ::String, client_id: ::String, request_body: Models::Operations::ClientGrantedScopesGetApiPostRequestBody).void }
        def initialize(service_id:, client_id:, request_body:)
          @service_id = service_id
          @client_id = client_id
          @request_body = request_body
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @service_id == other.service_id
          return false unless @client_id == other.client_id
          return false unless @request_body == other.request_body
          true
        end
      end
    end
  end
end
