# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Operations
    

      class DeviceVerificationApiRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # A service ID.
        field :service_id, ::String, { 'path_param': { 'field_name': 'serviceId', 'style': 'simple', 'explode': false } }

        field :device_verification_request, Models::Components::DeviceVerificationRequest, { 'request': { 'media_type': 'application/json' } }

        sig { params(service_id: ::String, device_verification_request: Models::Components::DeviceVerificationRequest).void }
        def initialize(service_id:, device_verification_request:)
          @service_id = service_id
          @device_verification_request = device_verification_request
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @service_id == other.service_id
          return false unless @device_verification_request == other.device_verification_request
          true
        end
      end
    end
  end
end
