# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Operations

      class FederationRegistrationApiRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # A service ID.
        field :service_id, ::String, { 'path_param': { 'field_name': 'serviceId', 'style': 'simple', 'explode': false } }

        field :federation_registration_request, Models::Components::FederationRegistrationRequest, { 'request': { 'media_type': 'application/json' } }

        sig { params(service_id: ::String, federation_registration_request: Models::Components::FederationRegistrationRequest).void }
        def initialize(service_id:, federation_registration_request:)
          @service_id = service_id
          @federation_registration_request = federation_registration_request
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @service_id == other.service_id
          return false unless @federation_registration_request == other.federation_registration_request
          true
        end
      end
    end
  end
end
