# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Operations
    

      class FederationConfigurationApiRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # A service ID.
        field :service_id, ::String, { 'path_param': { 'field_name': 'serviceId', 'style': 'simple', 'explode': false } }

        field :request_body, Crystalline::Nilable.new(Models::Operations::FederationConfigurationApiRequestBody), { 'request': { 'media_type': 'application/json' } }

        sig { params(service_id: ::String, request_body: T.nilable(Models::Operations::FederationConfigurationApiRequestBody)).void }
        def initialize(service_id:, request_body: nil)
          @service_id = service_id
          @request_body = request_body
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @service_id == other.service_id
          return false unless @request_body == other.request_body
          true
        end
      end
    end
  end
end
