# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Operations
    

      class HskCreateApiRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # A service ID.
        field :service_id, ::String, { 'path_param': { 'field_name': 'serviceId', 'style': 'simple', 'explode': false } }

        field :hsk_create_request, Models::Components::HskCreateRequest, { 'request': { 'media_type': 'application/json' } }

        sig { params(service_id: ::String, hsk_create_request: Models::Components::HskCreateRequest).void }
        def initialize(service_id:, hsk_create_request:)
          @service_id = service_id
          @hsk_create_request = hsk_create_request
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @service_id == other.service_id
          return false unless @hsk_create_request == other.hsk_create_request
          true
        end
      end
    end
  end
end
