# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Operations
    

      class IdtokenReissueApiRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # A service ID.
        field :service_id, ::String, { 'path_param': { 'field_name': 'serviceId', 'style': 'simple', 'explode': false } }

        field :idtoken_reissue_request, Crystalline::Nilable.new(Models::Components::IdtokenReissueRequest), { 'request': { 'media_type': 'application/json' } }

        sig { params(service_id: ::String, idtoken_reissue_request: T.nilable(Models::Components::IdtokenReissueRequest)).void }
        def initialize(service_id:, idtoken_reissue_request: nil)
          @service_id = service_id
          @idtoken_reissue_request = idtoken_reissue_request
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @service_id == other.service_id
          return false unless @idtoken_reissue_request == other.idtoken_reissue_request
          true
        end
      end
    end
  end
end
