# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Operations
    

      class JoseVerifyApiRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # A service ID.
        field :service_id, ::String, { 'path_param': { 'field_name': 'serviceId', 'style': 'simple', 'explode': false } }

        field :jose_verify_request, Crystalline::Nilable.new(Models::Components::JoseVerifyRequest), { 'request': { 'media_type': 'application/json' } }

        sig { params(service_id: ::String, jose_verify_request: T.nilable(Models::Components::JoseVerifyRequest)).void }
        def initialize(service_id:, jose_verify_request: nil)
          @service_id = service_id
          @jose_verify_request = jose_verify_request
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @service_id == other.service_id
          return false unless @jose_verify_request == other.jose_verify_request
          true
        end
      end
    end
  end
end
