# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Operations

      class ServiceUpdateApiRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # A service ID.
        field :service_id, ::String, { 'path_param': { 'field_name': 'serviceId', 'style': 'simple', 'explode': false } }

        field :service, Crystalline::Nilable.new(Models::Components::ServiceInput), { 'request': { 'media_type': 'application/json' } }

        sig { params(service_id: ::String, service: T.nilable(Models::Components::ServiceInput)).void }
        def initialize(service_id:, service: nil)
          @service_id = service_id
          @service = service
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @service_id == other.service_id
          return false unless @service == other.service
          true
        end
      end
    end
  end
end
