# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Authlete
  module Models
    module Operations
    

      class ServiceGetListApiRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Start index (inclusive) of the result set. The default value is 0. Must not be a negative number.
        field :start, Crystalline::Nilable.new(::Integer), { 'query_param': { 'field_name': 'start', 'style': 'form', 'explode': true } }
        # End index (exclusive) of the result set. The default value is 5. Must not be a negative number.
        field :end_, Crystalline::Nilable.new(::Integer), { 'query_param': { 'field_name': 'end', 'style': 'form', 'explode': true } }

        sig { params(start: T.nilable(::Integer), end_: T.nilable(::Integer)).void }
        def initialize(start: nil, end_: nil)
          @start = start
          @end_ = end_
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @start == other.start
          return false unless @end_ == other.end_
          true
        end
      end
    end
  end
end
