# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'faraday'
require 'faraday/multipart'
require 'faraday/retry'
require 'sorbet-runtime'
require_relative 'sdk_hooks/hooks'
require_relative 'utils/retries'

module Authlete
  extend T::Sig
  class DynamicClientRegistration
    extend T::Sig
    


    sig { params(sdk_config: SDKConfiguration).void }
    def initialize(sdk_config)
      @sdk_configuration = sdk_config
      
    end

    sig { params(base_url: String, url_variables: T.nilable(T::Hash[Symbol, T.any(String, T::Enum)])).returns(String) }
    def get_url(base_url:, url_variables: nil)
      sd_base_url, sd_options = @sdk_configuration.get_server_details

      if base_url.nil?
        base_url = sd_base_url
      end

      if url_variables.nil?
        url_variables = sd_options
      end

      return Utils.template_url base_url, url_variables
    end


    sig { params(request_body: Models::Operations::ClientRegistrationApiRequestBody, service_id: ::String, timeout_ms: T.nilable(Integer)).returns(Models::Operations::ClientRegistrationApiResponse) }
    def register(request_body:, service_id:, timeout_ms: nil)
      # register - Register Client
      # Register a client. This API is supposed to be used to implement a client registration endpoint that
      # complies with [RFC 7591](https://datatracker.ietf.org/doc/html/rfc7591) (OAuth 2.0 Dynamic Client
      # Registration Protocol).
      # ### Description
      # This API is supposed to be called from the within the implementation of the client registration
      # endpoint of the authorization server. The authorization server implementation should retrieve
      # the value of `action` from the response and take the following steps according to the value.
      # **INTERNAL\_SERVER\_ERROR**
      # When the value of `action` is `INTERNAL\_SERVER\_ERROR`, it means that the API call from the authorization
      # server implementation was wrong or that an error occurred in Authlete.
      # In either case, from a viewpoint of the client or developer, it is an error on the server side.
      # Therefore, the authorization server implementation should generate a response with "500 Internal
      # Server Error"s and `application/json`.
      # The value of `responseContent` is a JSON string which describes the error, so it can be used as
      # the entity body of the response.
      # The following illustrates the response which the authorization server implementation should generate
      # and return to the client or developer.
      # ```
      # HTTP/1.1 500 Internal Server Error
      # Content-Type: application/json
      # Cache-Control: no-store
      # Pragma: no-cache
      # {responseContent}
      # ```
      # The endpoint implementation may return another different response to the client or developer since
      # "500 Internal Server Error" is not required by the specification.
      # **BAD\_REQUEST**
      # When the value of `action` is `BAD\_REQUEST`, it means that the request from the client or developer
      # was wrong.
      # The authorization server implementation should generate a response with "400 Bad Request" and `application/json`.
      # The value of `responseContent` is a JSON string which describes the error, so it can be used
      # as the entity body of the response.
      # The following illustrates the response which the authorization server implementation should generate
      # and return to the client or developer.
      # ```
      # HTTP/1.1 400 Bad Request
      # Content-Type: application/json
      # Cache-Control: no-store
      # Pragma: no-cache
      # {responseContent}
      # ```
      # **CREATED**
      # When the value of `action` is `CREATED`, it means that the request from the client or developer is
      # valid.
      # The authorization server implementation should generate a response to the client or developer with
      # "201 CREATED" and `application/json`.
      # The `responseContent` a JSON string which can be used as the entity body of the response.
      # The following illustrates the response which the authorization server implementation should generate
      # and return to the client or developer.
      # ```
      # HTTP/1.1 201 CREATED
      # Content-Type: application/json
      # Cache-Control: no-store
      # Pragma: no-cache
      # {responseContent}
      # ```
      # 
      request = Models::Operations::ClientRegistrationApiRequest.new(
        service_id: service_id,
        request_body: request_body
      )
      url, params = @sdk_configuration.get_server_details
      base_url = Utils.template_url(url, params)
      url = Utils.generate_url(
        Models::Operations::ClientRegistrationApiRequest,
        base_url,
        '/api/{serviceId}/client/registration',
        request
      )
      headers = {}
      headers = T.cast(headers, T::Hash[String, String])
      req_content_type, data, form = Utils.serialize_request_body(request, false, false, :request_body, :json)
      headers['content-type'] = req_content_type
      raise StandardError, 'request body is required' if data.nil? && form.nil?

      if form
        body = Utils.encode_form(form)
      elsif Utils.match_content_type(req_content_type, 'application/x-www-form-urlencoded')
        body = URI.encode_www_form(T.cast(data, T::Hash[Symbol, Object]))
      else
        body = data
      end
      headers['Accept'] = 'application/json'
      headers['user-agent'] = @sdk_configuration.user_agent

      security = @sdk_configuration.security_source&.call

      timeout = (timeout_ms.to_f / 1000) unless timeout_ms.nil?
      timeout ||= @sdk_configuration.timeout
      

      connection = @sdk_configuration.client

      hook_ctx = SDKHooks::HookContext.new(
        config: @sdk_configuration,
        base_url: base_url,
        oauth2_scopes: [],
        operation_id: 'client_registration_api',
        security_source: @sdk_configuration.security_source
      )

      error = T.let(nil, T.nilable(StandardError))
      http_response = T.let(nil, T.nilable(Faraday::Response))
      
      
      begin
        http_response = T.must(connection).post(url) do |req|
          req.body = body
          req.headers.merge!(headers)
          req.options.timeout = timeout unless timeout.nil?
          Utils.configure_request_security(req, security)

          @sdk_configuration.hooks.before_request(
            hook_ctx: SDKHooks::BeforeRequestHookContext.new(
              hook_ctx: hook_ctx
            ),
            request: req
          )
        end
      rescue StandardError => e
        error = e
      ensure
        if http_response.nil? || Utils.error_status?(http_response.status)
          http_response = @sdk_configuration.hooks.after_error(
            error: error,
            hook_ctx: SDKHooks::AfterErrorHookContext.new(
              hook_ctx: hook_ctx
            ),
            response: http_response
          )
        else
          http_response = @sdk_configuration.hooks.after_success(
            hook_ctx: SDKHooks::AfterSuccessHookContext.new(
              hook_ctx: hook_ctx
            ),
            response: http_response
          )
        end
        
        if http_response.nil?
          raise error if !error.nil?
          raise 'no response'
        end
      end
      
      content_type = http_response.headers.fetch('Content-Type', 'application/octet-stream')
      if Utils.match_status_code(http_response.status, ['200'])
        if Utils.match_content_type(content_type, 'application/json')
          http_response = @sdk_configuration.hooks.after_success(
            hook_ctx: SDKHooks::AfterSuccessHookContext.new(
              hook_ctx: hook_ctx
            ),
            response: http_response
          )
          response_data = http_response.env.response_body
          obj = Crystalline.unmarshal_json(JSON.parse(response_data), Models::Components::ClientRegistrationResponse)
          response = Models::Operations::ClientRegistrationApiResponse.new(
            status_code: http_response.status,
            content_type: content_type,
            raw_response: http_response,
            client_registration_response: T.unsafe(obj)
          )

          return response
        else
          raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'Unknown content type received'
        end
      elsif Utils.match_status_code(http_response.status, ['400', '401', '403'])
        if Utils.match_content_type(content_type, 'application/json')
          http_response = @sdk_configuration.hooks.after_success(
            hook_ctx: SDKHooks::AfterSuccessHookContext.new(
              hook_ctx: hook_ctx
            ),
            response: http_response
          )
          response_data = http_response.env.response_body
          obj = Crystalline.unmarshal_json(JSON.parse(response_data), Models::Errors::ResultError)
          obj.raw_response = http_response
          throw obj
        else
          raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'Unknown content type received'
        end
      elsif Utils.match_status_code(http_response.status, ['500'])
        if Utils.match_content_type(content_type, 'application/json')
          http_response = @sdk_configuration.hooks.after_success(
            hook_ctx: SDKHooks::AfterSuccessHookContext.new(
              hook_ctx: hook_ctx
            ),
            response: http_response
          )
          response_data = http_response.env.response_body
          obj = Crystalline.unmarshal_json(JSON.parse(response_data), Models::Errors::ResultError)
          obj.raw_response = http_response
          throw obj
        else
          raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'Unknown content type received'
        end
      elsif Utils.match_status_code(http_response.status, ['4XX'])
        raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'API error occurred'
      elsif Utils.match_status_code(http_response.status, ['5XX'])
        raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'API error occurred'
      else
        raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'Unknown status code received'

      end
    end


    sig { params(request_body: Models::Operations::ClientRegistrationGetApiRequestBody, service_id: ::String, timeout_ms: T.nilable(Integer)).returns(Models::Operations::ClientRegistrationGetApiResponse) }
    def retrieve(request_body:, service_id:, timeout_ms: nil)
      # retrieve - Get Client
      # Get a dynamically registered client. This API is supposed to be used to implement a client registration
      # management endpoint that complies with [RFC 7592](https://datatracker.ietf.org/doc/html/rfc7592)
      # (OAuth 2.0 Dynamic Registration Management).
      # ### Description
      # This API is supposed to be called from the within the implementation of the client registration
      # management endpoint of the authorization server. The authorization server implementation should
      # retrieve the value of `action` from the response and take the following steps according to the value.
      # **INTERNAL\_SERVER\_ERROR**
      # When the value of `action` is `INTERNAL\_SERVER\_ERROR`, it means that the API call from the authorization
      # server implementation was wrong or that an error occurred in Authlete.
      # In either case, from a viewpoint of the client or developer, it is an error on the server side.
      # Therefore, the authorization server implementation should generate a response to the client or developer
      # with "500 Internal Server Error"s and `application/json`.
      # The value of `responseContent` is a JSON string which describes the error, so it can be used as
      # the entity body of the response.
      # The following illustrates the response which the authorization server implementation should generate
      # and return to the client or developer.
      # ```
      # HTTP/1.1 500 Internal Server Error
      # Content-Type: application/json
      # Cache-Control: no-store
      # Pragma: no-cache
      # {responseContent}
      # ```
      # The endpoint implementation may return another different response to the client or developer since
      # "500 Internal Server Error" is not required by the specification.
      # **BAD\_REQUEST**
      # When the value of `action` is `BAD\_REQUEST`, it means that the request from the client or developer
      # was wrong.
      # The authorization server implementation should generate a response to the client or developer with
      # "400 Bad Request" and `application/json`.
      # The value of `responseContent` is a JSON string which describes the error, so it can be used as
      # the entity body of the response.
      # The following illustrates the response which the authorization server implementation should generate
      # and return to the client or developer.
      # ```
      # HTTP/1.1 400 Bad Request
      # Content-Type: application/json
      # Cache-Control: no-store
      # Pragma: no-cache
      # {responseContent}
      # ```
      # **UNAUTHORIZED**
      # When the value of `action` is `UNAUTHORIZED`, it means that the registration access token used by
      # the client configuration request (RFC 7592) is invalid, or the client application which the token
      # is tied to does not exist any longer or is invalid.
      # The HTTP status of the response returned to the client application must be "401 Unauthorized" and
      # the content type must be `application/json`.
      # The value of `responseContent` is a JSON string which describes the error, so it can be used as
      # the entity body of the response.
      # The following illustrates the response which the endpoint implementation should generate and return
      # to the client application.
      # ```
      # HTTP/1.1 401 Unauthorized
      # Content-Type: application/json
      # Cache-Control: no-store
      # Pragma: no-cache
      # {responseContent}
      # ```
      # NOTE: The `UNAUTHORIZED` value was added in October, 2021. See the description of
      # `Service.unauthorizedOnClientConfigSupported` for details.
      # **OK**
      # When the value of `action` is `OK`, it means that the request from the client or developer is valid.
      # The authorization server implementation should generate a response to the client or developer with
      # "200 OK" and `application/json`.
      # The `responseContent` a JSON string which can be used as the entity body of the response.
      # The following illustrates the response which the authorization server implementation should generate
      # and return to the client or developer.
      # ```
      # HTTP/1.1 200 OK
      # Content-Type: application/json
      # Cache-Control: no-store
      # Pragma: no-cache
      # {responseContent}
      # ```
      # 
      request = Models::Operations::ClientRegistrationGetApiRequest.new(
        service_id: service_id,
        request_body: request_body
      )
      url, params = @sdk_configuration.get_server_details
      base_url = Utils.template_url(url, params)
      url = Utils.generate_url(
        Models::Operations::ClientRegistrationGetApiRequest,
        base_url,
        '/api/{serviceId}/client/registration/get',
        request
      )
      headers = {}
      headers = T.cast(headers, T::Hash[String, String])
      req_content_type, data, form = Utils.serialize_request_body(request, false, false, :request_body, :json)
      headers['content-type'] = req_content_type
      raise StandardError, 'request body is required' if data.nil? && form.nil?

      if form
        body = Utils.encode_form(form)
      elsif Utils.match_content_type(req_content_type, 'application/x-www-form-urlencoded')
        body = URI.encode_www_form(T.cast(data, T::Hash[Symbol, Object]))
      else
        body = data
      end
      headers['Accept'] = 'application/json'
      headers['user-agent'] = @sdk_configuration.user_agent

      security = @sdk_configuration.security_source&.call

      timeout = (timeout_ms.to_f / 1000) unless timeout_ms.nil?
      timeout ||= @sdk_configuration.timeout
      

      connection = @sdk_configuration.client

      hook_ctx = SDKHooks::HookContext.new(
        config: @sdk_configuration,
        base_url: base_url,
        oauth2_scopes: [],
        operation_id: 'client_registration_get_api',
        security_source: @sdk_configuration.security_source
      )

      error = T.let(nil, T.nilable(StandardError))
      http_response = T.let(nil, T.nilable(Faraday::Response))
      
      
      begin
        http_response = T.must(connection).post(url) do |req|
          req.body = body
          req.headers.merge!(headers)
          req.options.timeout = timeout unless timeout.nil?
          Utils.configure_request_security(req, security)

          @sdk_configuration.hooks.before_request(
            hook_ctx: SDKHooks::BeforeRequestHookContext.new(
              hook_ctx: hook_ctx
            ),
            request: req
          )
        end
      rescue StandardError => e
        error = e
      ensure
        if http_response.nil? || Utils.error_status?(http_response.status)
          http_response = @sdk_configuration.hooks.after_error(
            error: error,
            hook_ctx: SDKHooks::AfterErrorHookContext.new(
              hook_ctx: hook_ctx
            ),
            response: http_response
          )
        else
          http_response = @sdk_configuration.hooks.after_success(
            hook_ctx: SDKHooks::AfterSuccessHookContext.new(
              hook_ctx: hook_ctx
            ),
            response: http_response
          )
        end
        
        if http_response.nil?
          raise error if !error.nil?
          raise 'no response'
        end
      end
      
      content_type = http_response.headers.fetch('Content-Type', 'application/octet-stream')
      if Utils.match_status_code(http_response.status, ['200'])
        if Utils.match_content_type(content_type, 'application/json')
          http_response = @sdk_configuration.hooks.after_success(
            hook_ctx: SDKHooks::AfterSuccessHookContext.new(
              hook_ctx: hook_ctx
            ),
            response: http_response
          )
          response_data = http_response.env.response_body
          obj = Crystalline.unmarshal_json(JSON.parse(response_data), Models::Components::ClientRegistrationResponse)
          response = Models::Operations::ClientRegistrationGetApiResponse.new(
            status_code: http_response.status,
            content_type: content_type,
            raw_response: http_response,
            client_registration_response: T.unsafe(obj)
          )

          return response
        else
          raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'Unknown content type received'
        end
      elsif Utils.match_status_code(http_response.status, ['400', '401', '403'])
        if Utils.match_content_type(content_type, 'application/json')
          http_response = @sdk_configuration.hooks.after_success(
            hook_ctx: SDKHooks::AfterSuccessHookContext.new(
              hook_ctx: hook_ctx
            ),
            response: http_response
          )
          response_data = http_response.env.response_body
          obj = Crystalline.unmarshal_json(JSON.parse(response_data), Models::Errors::ResultError)
          obj.raw_response = http_response
          throw obj
        else
          raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'Unknown content type received'
        end
      elsif Utils.match_status_code(http_response.status, ['500'])
        if Utils.match_content_type(content_type, 'application/json')
          http_response = @sdk_configuration.hooks.after_success(
            hook_ctx: SDKHooks::AfterSuccessHookContext.new(
              hook_ctx: hook_ctx
            ),
            response: http_response
          )
          response_data = http_response.env.response_body
          obj = Crystalline.unmarshal_json(JSON.parse(response_data), Models::Errors::ResultError)
          obj.raw_response = http_response
          throw obj
        else
          raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'Unknown content type received'
        end
      elsif Utils.match_status_code(http_response.status, ['4XX'])
        raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'API error occurred'
      elsif Utils.match_status_code(http_response.status, ['5XX'])
        raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'API error occurred'
      else
        raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'Unknown status code received'

      end
    end


    sig { params(request_body: Models::Operations::ClientRegistrationUpdateApiRequestBody, service_id: ::String, timeout_ms: T.nilable(Integer)).returns(Models::Operations::ClientRegistrationUpdateApiResponse) }
    def update(request_body:, service_id:, timeout_ms: nil)
      # update - Update Client
      # Update a dynamically registered client. This API is supposed to be used to implement a client
      # registration management endpoint that complies with [RFC 7592](https://datatracker.ietf.org/doc/html/rfc7592)
      # (OAuth 2.0 Dynamic Registration Management).
      # ### Description
      # This API is supposed to be called from the within the implementation of the client registration
      # management endpoint of the authorization server. The authorization server implementation should
      # retrieve the value of `action` from the response and take the following steps according to the value.
      # **INTERNAL\_SERVER\_ERROR**
      # When the value of `action` is `INTERNAL\_SERVER\_ERROR`, it means that the API call from the authorization
      # server implementation was wrong or that an error occurred in Authlete.
      # In either case, from a viewpoint of the client or developer, it is an error on the server side.
      # Therefore, the authorization server implementation should generate a response with "500 Internal
      # Server Error"s and `application/json`.
      # The value of `responseContent` is a JSON string which describes the error, so it can be used as
      # the entity body of the response.
      # The following illustrates the response which the authorization server implementation should generate
      # and return to the client or developer.
      # ```
      # HTTP/1.1 500 Internal Server Error
      # Content-Type: application/json
      # Cache-Control: no-store
      # Pragma: no-cache
      # {responseContent}
      # ```
      # The endpoint implementation may return another different response to the client or developer since
      # "500 Internal Server Error" is not required by the specification.
      # **BAD\_REQUEST**
      # When the value of `action` is `BAD\_REQUEST`, it means that the request from the client or developer
      # was wrong.
      # The authorization server implementation should generate a response with "400 Bad Request" and `application/json`.
      # The value of `responseContent` is a JSON string which describes the error, so it can be used as
      # the entity body of the response.
      # The following illustrates the response which the authorization server implementation should generate
      # and return to the client or developer.
      # ```
      # HTTP/1.1 400 Bad Request
      # Content-Type: application/json
      # Cache-Control: no-store
      # Pragma: no-cache
      # {responseContent}
      # ```
      # **UNAUTHORIZED**
      # When the value of `action` is `UNAUTHORIZED`, it means that the registration access token used by
      # the client configuration request (RFC 7592) is invalid, or the client application which the token
      # is tied to does not exist any longer or is invalid.
      # The HTTP status of the response returned to the client application must be "401 Unauthorized" and
      # the content type must be `application/json`.
      # The value of `responseContent` is a JSON string which describes the error, so it can be used as
      # the entity body of the response.
      # The following illustrates the response which the endpoint implementation should generate and return
      # to the client application.
      # ```
      # HTTP/1.1 401 Unauthorized
      # Content-Type: application/json
      # Cache-Control: no-store
      # Pragma: no-cache
      # {responseContent}
      # ```
      # NOTE: The `UNAUTHORIZED` value was added in October, 2021. See the description of
      # `Service.unauthorizedOnClientConfigSupported` for details.
      # **UPDATED**
      # When the value of `action` is `UPDATED`, it means that the request from the client or developer is
      # valid.
      # The authorization server implementation should generate a response to the client or developer with
      # "200 OK" and `application/json`.
      # The `responseContent` a JSON string which can be used as the entity body of the response.
      # The following illustrates the response which the authorization server implementation should generate
      # and return to the client or developer.
      # ```
      # HTTP/1.1 200 OK
      # Content-Type: application/json
      # Cache-Control: no-store
      # Pragma: no-cache
      # {responseContent}
      # ```
      # 
      request = Models::Operations::ClientRegistrationUpdateApiRequest.new(
        service_id: service_id,
        request_body: request_body
      )
      url, params = @sdk_configuration.get_server_details
      base_url = Utils.template_url(url, params)
      url = Utils.generate_url(
        Models::Operations::ClientRegistrationUpdateApiRequest,
        base_url,
        '/api/{serviceId}/client/registration/update',
        request
      )
      headers = {}
      headers = T.cast(headers, T::Hash[String, String])
      req_content_type, data, form = Utils.serialize_request_body(request, false, false, :request_body, :json)
      headers['content-type'] = req_content_type
      raise StandardError, 'request body is required' if data.nil? && form.nil?

      if form
        body = Utils.encode_form(form)
      elsif Utils.match_content_type(req_content_type, 'application/x-www-form-urlencoded')
        body = URI.encode_www_form(T.cast(data, T::Hash[Symbol, Object]))
      else
        body = data
      end
      headers['Accept'] = 'application/json'
      headers['user-agent'] = @sdk_configuration.user_agent

      security = @sdk_configuration.security_source&.call

      timeout = (timeout_ms.to_f / 1000) unless timeout_ms.nil?
      timeout ||= @sdk_configuration.timeout
      

      connection = @sdk_configuration.client

      hook_ctx = SDKHooks::HookContext.new(
        config: @sdk_configuration,
        base_url: base_url,
        oauth2_scopes: [],
        operation_id: 'client_registration_update_api',
        security_source: @sdk_configuration.security_source
      )

      error = T.let(nil, T.nilable(StandardError))
      http_response = T.let(nil, T.nilable(Faraday::Response))
      
      
      begin
        http_response = T.must(connection).post(url) do |req|
          req.body = body
          req.headers.merge!(headers)
          req.options.timeout = timeout unless timeout.nil?
          Utils.configure_request_security(req, security)

          @sdk_configuration.hooks.before_request(
            hook_ctx: SDKHooks::BeforeRequestHookContext.new(
              hook_ctx: hook_ctx
            ),
            request: req
          )
        end
      rescue StandardError => e
        error = e
      ensure
        if http_response.nil? || Utils.error_status?(http_response.status)
          http_response = @sdk_configuration.hooks.after_error(
            error: error,
            hook_ctx: SDKHooks::AfterErrorHookContext.new(
              hook_ctx: hook_ctx
            ),
            response: http_response
          )
        else
          http_response = @sdk_configuration.hooks.after_success(
            hook_ctx: SDKHooks::AfterSuccessHookContext.new(
              hook_ctx: hook_ctx
            ),
            response: http_response
          )
        end
        
        if http_response.nil?
          raise error if !error.nil?
          raise 'no response'
        end
      end
      
      content_type = http_response.headers.fetch('Content-Type', 'application/octet-stream')
      if Utils.match_status_code(http_response.status, ['200'])
        if Utils.match_content_type(content_type, 'application/json')
          http_response = @sdk_configuration.hooks.after_success(
            hook_ctx: SDKHooks::AfterSuccessHookContext.new(
              hook_ctx: hook_ctx
            ),
            response: http_response
          )
          response_data = http_response.env.response_body
          obj = Crystalline.unmarshal_json(JSON.parse(response_data), Models::Components::ClientRegistrationResponse)
          response = Models::Operations::ClientRegistrationUpdateApiResponse.new(
            status_code: http_response.status,
            content_type: content_type,
            raw_response: http_response,
            client_registration_response: T.unsafe(obj)
          )

          return response
        else
          raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'Unknown content type received'
        end
      elsif Utils.match_status_code(http_response.status, ['400', '401', '403'])
        if Utils.match_content_type(content_type, 'application/json')
          http_response = @sdk_configuration.hooks.after_success(
            hook_ctx: SDKHooks::AfterSuccessHookContext.new(
              hook_ctx: hook_ctx
            ),
            response: http_response
          )
          response_data = http_response.env.response_body
          obj = Crystalline.unmarshal_json(JSON.parse(response_data), Models::Errors::ResultError)
          obj.raw_response = http_response
          throw obj
        else
          raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'Unknown content type received'
        end
      elsif Utils.match_status_code(http_response.status, ['500'])
        if Utils.match_content_type(content_type, 'application/json')
          http_response = @sdk_configuration.hooks.after_success(
            hook_ctx: SDKHooks::AfterSuccessHookContext.new(
              hook_ctx: hook_ctx
            ),
            response: http_response
          )
          response_data = http_response.env.response_body
          obj = Crystalline.unmarshal_json(JSON.parse(response_data), Models::Errors::ResultError)
          obj.raw_response = http_response
          throw obj
        else
          raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'Unknown content type received'
        end
      elsif Utils.match_status_code(http_response.status, ['4XX'])
        raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'API error occurred'
      elsif Utils.match_status_code(http_response.status, ['5XX'])
        raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'API error occurred'
      else
        raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'Unknown status code received'

      end
    end


    sig { params(request_body: Models::Operations::ClientRegistrationDeleteApiRequestBody, service_id: ::String, timeout_ms: T.nilable(Integer)).returns(Models::Operations::ClientRegistrationDeleteApiResponse) }
    def destroy(request_body:, service_id:, timeout_ms: nil)
      # destroy - Delete Client
      # Delete a dynamically registered client. This API is supposed to be used to implement a client
      # registration management endpoint that complies with [RFC 7592](https://datatracker.ietf.org/doc/html/rfc7592)
      # (OAuth 2.0 Dynamic Registration Management).
      # ### Description
      # This API is supposed to be called from the within the implementation of the client registration
      # management endpoint of the authorization server. The authorization server implementation should
      # retrieve the value of `action` from the response and take the following steps according to the value.
      # **INTERNAL\_SERVER\_ERROR**
      # When the value of `action` is `INTERNAL\_SERVER\_ERROR`, it means that the API call from the authorization
      # server implementation was wrong or that an error occurred in Authlete.
      # In either case, from a viewpoint of the client or developer, it is an error on the server side.
      # Therefore, the authorization server implementation should generate a response with "500 Internal
      # Server Error"s and `application/json`.
      # The value of `responseContent` is a JSON string which describes the error, so it can be used as
      # the entity body of the response.
      # The following illustrates the response which the authorization server implementation should generate
      # and return to the client or developer.
      # ```
      # HTTP/1.1 500 Internal Server Error
      # Content-Type: application/json
      # Cache-Control: no-store
      # Pragma: no-cache
      # {responseContent}
      # ```
      # The endpoint implementation may return another different response to the client or developer since
      # "500 Internal Server Error" is not required by the specification.
      # **BAD\_REQUEST**
      # When the value of `action` is `BAD\_REQUEST`, it means that the request from the client or developer
      # was wrong.
      # The authorization server implementation should generate a response with "400 Bad Request" and `application/json`.
      # The value of `responseContent` is a JSON string which describes the error, so it can be used as
      # the entity body of the response.
      # The following illustrates the response which the authorization server implementation should generate
      # and return to the client or developer.
      # ```
      # HTTP/1.1 400 Bad Request
      # Content-Type: application/json
      # Cache-Control: no-store
      # Pragma: no-cache
      # {responseContent}
      # ```
      # **UNAUTHORIZED**
      # When the value of `action` is `UNAUTHORIZED`, it means that the registration access token used by
      # the client configuration request (RFC 7592) is invalid, or the client application which the token
      # is tied to does not exist any longer or is invalid.
      # The HTTP status of the response returned to the client application must be "401 Unauthorized" and
      # the content type must be `application/json`.
      # The value of `responseContent` is a JSON string which describes the error, so it can be used as
      # the entity body of the response.
      # The following illustrates the response which the endpoint implementation should generate and return
      # to the client application.
      # ```
      # HTTP/1.1 401 Unauthorized
      # Content-Type: application/json
      # Cache-Control: no-store
      # Pragma: no-cache
      # {responseContent}
      # ```
      # NOTE: The `UNAUTHORIZED` value was added in October, 2021. See the description of
      # `Service.unauthorizedOnClientConfigSupported` for details.
      # **DELETED**
      # When the value of `action` is `DELETED`, it means that the request from the client or developer is
      # valid.
      # The authorization server implementation should generate a response to the client or developer with
      # "204 No Content".
      # The following illustrates the response which the authorization server implementation should generate
      # and return to the client or developer.
      # ```
      # HTTP/1.1 204 No Content
      # Cache-Control: no-store
      # Pragma: no-cache
      # ```
      # 
      request = Models::Operations::ClientRegistrationDeleteApiRequest.new(
        service_id: service_id,
        request_body: request_body
      )
      url, params = @sdk_configuration.get_server_details
      base_url = Utils.template_url(url, params)
      url = Utils.generate_url(
        Models::Operations::ClientRegistrationDeleteApiRequest,
        base_url,
        '/api/{serviceId}/client/registration/delete',
        request
      )
      headers = {}
      headers = T.cast(headers, T::Hash[String, String])
      req_content_type, data, form = Utils.serialize_request_body(request, false, false, :request_body, :json)
      headers['content-type'] = req_content_type
      raise StandardError, 'request body is required' if data.nil? && form.nil?

      if form
        body = Utils.encode_form(form)
      elsif Utils.match_content_type(req_content_type, 'application/x-www-form-urlencoded')
        body = URI.encode_www_form(T.cast(data, T::Hash[Symbol, Object]))
      else
        body = data
      end
      headers['Accept'] = 'application/json'
      headers['user-agent'] = @sdk_configuration.user_agent

      security = @sdk_configuration.security_source&.call

      timeout = (timeout_ms.to_f / 1000) unless timeout_ms.nil?
      timeout ||= @sdk_configuration.timeout
      

      connection = @sdk_configuration.client

      hook_ctx = SDKHooks::HookContext.new(
        config: @sdk_configuration,
        base_url: base_url,
        oauth2_scopes: [],
        operation_id: 'client_registration_delete_api',
        security_source: @sdk_configuration.security_source
      )

      error = T.let(nil, T.nilable(StandardError))
      http_response = T.let(nil, T.nilable(Faraday::Response))
      
      
      begin
        http_response = T.must(connection).post(url) do |req|
          req.body = body
          req.headers.merge!(headers)
          req.options.timeout = timeout unless timeout.nil?
          Utils.configure_request_security(req, security)

          @sdk_configuration.hooks.before_request(
            hook_ctx: SDKHooks::BeforeRequestHookContext.new(
              hook_ctx: hook_ctx
            ),
            request: req
          )
        end
      rescue StandardError => e
        error = e
      ensure
        if http_response.nil? || Utils.error_status?(http_response.status)
          http_response = @sdk_configuration.hooks.after_error(
            error: error,
            hook_ctx: SDKHooks::AfterErrorHookContext.new(
              hook_ctx: hook_ctx
            ),
            response: http_response
          )
        else
          http_response = @sdk_configuration.hooks.after_success(
            hook_ctx: SDKHooks::AfterSuccessHookContext.new(
              hook_ctx: hook_ctx
            ),
            response: http_response
          )
        end
        
        if http_response.nil?
          raise error if !error.nil?
          raise 'no response'
        end
      end
      
      content_type = http_response.headers.fetch('Content-Type', 'application/octet-stream')
      if Utils.match_status_code(http_response.status, ['200'])
        if Utils.match_content_type(content_type, 'application/json')
          http_response = @sdk_configuration.hooks.after_success(
            hook_ctx: SDKHooks::AfterSuccessHookContext.new(
              hook_ctx: hook_ctx
            ),
            response: http_response
          )
          response_data = http_response.env.response_body
          obj = Crystalline.unmarshal_json(JSON.parse(response_data), Models::Components::ClientRegistrationResponse)
          response = Models::Operations::ClientRegistrationDeleteApiResponse.new(
            status_code: http_response.status,
            content_type: content_type,
            raw_response: http_response,
            client_registration_response: T.unsafe(obj)
          )

          return response
        else
          raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'Unknown content type received'
        end
      elsif Utils.match_status_code(http_response.status, ['400', '401', '403'])
        if Utils.match_content_type(content_type, 'application/json')
          http_response = @sdk_configuration.hooks.after_success(
            hook_ctx: SDKHooks::AfterSuccessHookContext.new(
              hook_ctx: hook_ctx
            ),
            response: http_response
          )
          response_data = http_response.env.response_body
          obj = Crystalline.unmarshal_json(JSON.parse(response_data), Models::Errors::ResultError)
          obj.raw_response = http_response
          throw obj
        else
          raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'Unknown content type received'
        end
      elsif Utils.match_status_code(http_response.status, ['500'])
        if Utils.match_content_type(content_type, 'application/json')
          http_response = @sdk_configuration.hooks.after_success(
            hook_ctx: SDKHooks::AfterSuccessHookContext.new(
              hook_ctx: hook_ctx
            ),
            response: http_response
          )
          response_data = http_response.env.response_body
          obj = Crystalline.unmarshal_json(JSON.parse(response_data), Models::Errors::ResultError)
          obj.raw_response = http_response
          throw obj
        else
          raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'Unknown content type received'
        end
      elsif Utils.match_status_code(http_response.status, ['4XX'])
        raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'API error occurred'
      elsif Utils.match_status_code(http_response.status, ['5XX'])
        raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'API error occurred'
      else
        raise ::Authlete::Models::Errors::APIError.new(status_code: http_response.status, body: http_response.env.response_body, raw_response: http_response), 'Unknown status code received'

      end
    end
  end
end
