# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'faraday'
require 'faraday/multipart'
require 'faraday/retry'
require 'sorbet-runtime'
require_relative 'sdk_hooks/hooks'
require_relative 'utils/retries'

module Authlete
  extend T::Sig

  SERVERS = [
    'https://us.authlete.com', # 1 - 🇺🇸 US Cluster
    'https://jp.authlete.com', # 1 - 🇯🇵 Japan Cluster
    'https://eu.authlete.com', # 1 - 🇪🇺 Europe Cluster
    'https://br.authlete.com', # 1 - 🇧🇷 Brazil Cluster
  ].freeze
  SERVERS = T.let(SERVERS, T::Array[String])
  # Contains the list of servers available to the SDK

  class SDKConfiguration
    extend T::Sig

    sig { returns(T.nilable(Faraday::Connection)) }
    attr_accessor :client

    sig { returns(::Authlete::SDKHooks::Hooks) }
    attr_accessor :hooks

    sig { returns(T.nilable(::Authlete::Utils::RetryConfig)) }
    attr_accessor :retry_config

    sig { returns(T.nilable(Float)) }
    attr_accessor :timeout

    
    sig { returns(T.nilable(T.proc.returns(T.nilable(Models::Components::Security)))) }
    attr_accessor :security_source

    
    sig { returns(T.nilable(String)) }
    attr_accessor :server_url

    
    sig { returns(T.nilable(Integer)) }
    attr_accessor :server_idx

    
    sig { returns(String) }
    attr_accessor :language

    sig { returns(String) }
    attr_accessor :openapi_doc_version

    sig { returns(String) }
    attr_accessor :sdk_version

    sig { returns(String) }
    attr_accessor :gen_version

    sig { returns(String) }
    attr_accessor :user_agent

    sig do
      params(
        client: T.nilable(Faraday::Connection),
        hooks: ::Authlete::SDKHooks::Hooks,
        retry_config: T.nilable(::Authlete::Utils::RetryConfig),
        timeout_ms: T.nilable(Integer),
        bearer: T.nilable(::String),
        security_source: T.nilable(T.proc.returns(Models::Components::Security)),
        server_url: T.nilable(String),
        server_idx: T.nilable(Integer)
      ).void
    end
    def initialize(client, hooks, retry_config, timeout_ms, bearer, security_source, server_url, server_idx)
      @client = client
      @hooks = hooks
      @retry_config = retry_config
      @server_url = server_url
      @timeout = (timeout_ms.to_f / 1000) unless timeout_ms.nil?
      @server_idx = server_idx.nil? ? 0 : server_idx
      raise StandardError, "Invalid server index #{server_idx}" if @server_idx.negative? || @server_idx >= SERVERS.length
      if !security_source.nil?
        @security_source = security_source
      elsif !bearer.nil?
        @security_source = -> { Models::Components::Security.new(bearer: bearer) }
      end
      @language = 'ruby'
      @openapi_doc_version = '3.0.16'
      @sdk_version = '0.0.1.beta'
      @gen_version = '2.788.5'
      @user_agent = 'speakeasy-sdk/ruby 0.0.1.beta 2.788.5 3.0.16 authlete_ruby_sdk'
    end

    sig { returns([String, T::Hash[Symbol, String]]) }
    def get_server_details
      return [@server_url.delete_suffix('/'), {}] if !@server_url.nil?
      @server_idx = T.must(@server_idx)
      [T.must(SERVERS[@server_idx]), {}]
    end
  end
end
